# Generated by Django 5.2.17 on 2026-09-21 18:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('exchanges', '0002_exchangeholiday_affected_product_groups_and_more'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('symbol_root', models.CharField(db_index=True, help_text='Exchange ticker root (e.g. CL, B, NG, ZC, ZS, GC, HG, CA, FCPO, CRUDEOIL).', max_length=20)),
                ('name', models.CharField(help_text='Full commercial name of contract (e.g. Light Sweet Crude Oil Futures).', max_length=150)),
                ('instrument_type', models.CharField(choices=[('FUTURES', 'Physical/Cash Futures'), ('OPTIONS_AMERICAN', 'American Vanilla Options'), ('OPTIONS_EUROPEAN', 'European Vanilla Options'), ('CALENDAR_SPREAD', 'Calendar Spread'), ('BASIS_SWAP', 'Basis Swap')], default='FUTURES', help_text='Instrument classification.', max_length=30)),
                ('contract_size', models.DecimalField(decimal_places=4, help_text='Contract multiplier quantity (e.g. 1000 for CL = 1,000 barrels).', max_digits=14)),
                ('minimum_tick_size', models.DecimalField(decimal_places=6, default=Decimal('0.01'), help_text='Minimum allowable price fluctuation.', max_digits=12)),
                ('tick_value', models.DecimalField(decimal_places=4, default=Decimal('10.00'), help_text='Monetary value of a minimum tick move per contract.', max_digits=12)),
                ('trading_currency', models.CharField(default='USD', help_text='ISO currency in which the contract prices and settles.', max_length=5)),
                ('settlement_method', models.CharField(choices=[('PHYSICAL', 'Physical Delivery'), ('CASH', 'Cash Settled')], default='PHYSICAL', help_text='Binary settlement mechanism: Physical delivery vs Cash settlement.', max_length=20)),
                ('trading_months', models.CharField(default='ALL_12', help_text="Comma-separated month codes (e.g. 'F,G,H,J,K,M,N,Q,U,V,X,Z' or 'F,H,K,N,U,X,Z').", max_length=100)),
                ('expiry_rule', models.CharField(choices=[('DAYS_BEFORE_MONTH_START', 'N Business Days Before Delivery Month Start'), ('DAY_OF_PRIOR_MONTH_WITH_BUS_OFFSET', 'Specific Calendar Day of Prior Month (Rolled to Prior Business Day)'), ('BUSINESS_DAY_BEFORE_DAY_OF_MONTH', 'Business Day Preceding Specific Day of Delivery Month'), ('LAST_BUSINESS_DAY_OF_PRIOR_MONTH', 'Last Business Day of Month Preceding Delivery Month'), ('LAST_BUSINESS_DAY_OF_TWO_MONTHS_PRIOR', 'Last Business Day of Second Month Preceding Delivery Month'), ('THIRD_WEDNESDAY_OF_MONTH', 'Third Wednesday of Delivery Month'), ('FIFTH_BUSINESS_DAY_BEFORE_MONTH_END', 'Nth Business Day Preceding Contract Month End')], default='DAY_OF_PRIOR_MONTH_WITH_BUS_OFFSET', help_text='Algorithmic rule used to determine the last trading day.', max_length=50)),
                ('expiry_rule_parameter', models.IntegerField(default=25, help_text='Rule parameter (e.g. 25 for 25th day of month, 3 for 3 business days offset).')),
                ('notice_rule', models.CharField(blank=True, default='First business day prior to first delivery day', help_text='Contract first notice day rule description.', max_length=200)),
                ('default_roll_rule', models.CharField(default='GSCI_5_TO_9_BUS_DAY', help_text='Benchmark roll schedule (e.g. GSCI 5-9 business days, BCOM 6-10 business days).', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this specification is actively traded.')),
                ('display_order', models.PositiveIntegerField(default=100, help_text='Sorting order in dashboards and analytical tables.')),
                ('commodity', models.ForeignKey(help_text='Canonical physical commodity underpinning this derivative contract.', on_delete=django.db.models.deletion.CASCADE, related_name='contract_specifications', to='commodities.commoditymaster')),
                ('contract_unit', models.ForeignKey(help_text='Unit of measure for the contract size (e.g. BBL, BU, MT, TOZ).', on_delete=django.db.models.deletion.PROTECT, related_name='contract_size_specs', to='metadata.unitmaster')),
                ('exchange', models.ForeignKey(help_text='Operating exchange venue listing this contract.', on_delete=django.db.models.deletion.CASCADE, related_name='contract_specifications', to='exchanges.exchangemaster')),
                ('price_quote_unit', models.ForeignKey(help_text='Quotation unit of measure (e.g. USD/bbl, USC/bu, USD/t, INR/bbl).', on_delete=django.db.models.deletion.PROTECT, related_name='price_quote_specs', to='metadata.unitmaster')),
            ],
            options={
                'verbose_name': 'Contract Specification',
                'verbose_name_plural': 'Contract Specifications',
                'db_table': 'contracts_specification',
                'ordering': ['display_order', 'exchange', 'symbol_root'],
                'unique_together': {('exchange', 'symbol_root')},
            },
        ),
        migrations.CreateModel(
            name='ContractExpiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('contract_symbol', models.CharField(db_index=True, help_text='Full standardized ticker symbol (e.g. CLZ26, BRENTF27, ZCH27).', max_length=30)),
                ('contract_year', models.PositiveSmallIntegerField(db_index=True, help_text='4-digit contract delivery year (e.g. 2026).')),
                ('contract_month', models.PositiveSmallIntegerField(db_index=True, help_text='Contract delivery month (1-12).')),
                ('contract_month_code', models.CharField(choices=[('F', 'January (F)'), ('G', 'February (G)'), ('H', 'March (H)'), ('J', 'April (J)'), ('K', 'May (K)'), ('M', 'June (M)'), ('N', 'July (N)'), ('Q', 'August (Q)'), ('U', 'September (U)'), ('V', 'October (V)'), ('X', 'November (X)'), ('Z', 'December (Z)')], help_text='Standard futures month letter (F-Z).', max_length=2)),
                ('last_trading_day', models.DateField(db_index=True, help_text='Exact calculated last trading / expiration date.')),
                ('first_notice_day', models.DateField(blank=True, help_text='First date exchange issues delivery notices (physical contracts only).', null=True)),
                ('last_delivery_day', models.DateField(blank=True, help_text='Final physical transfer date (physical contracts only).', null=True)),
                ('final_settlement_date', models.DateField(help_text='Date on which cash settlement or physical invoice is finalized.')),
                ('is_expired', models.BooleanField(db_index=True, default=False, help_text='Whether this delivery contract has completed trading and settled.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether contract is actively monitored.')),
                ('specification', models.ForeignKey(help_text='Parent contract specification.', on_delete=django.db.models.deletion.CASCADE, related_name='expiries', to='contracts.contractspecification')),
            ],
            options={
                'verbose_name': 'Contract Expiry',
                'verbose_name_plural': 'Contract Expiries',
                'db_table': 'contracts_expiry',
                'ordering': ['specification', 'contract_year', 'contract_month'],
                'unique_together': {('specification', 'contract_year', 'contract_month')},
            },
        ),
    ]
