"""
Static Canonical Commodity Reference Catalog Provider.
Provides institutional specifications for 26 benchmark global physical commodities across 7 sectors
mapped to their active, liquid multi-exchange listings (NYMEX, ICE, CBOT, COMEX, LME, BMD, MCX, SGX, SHFE, DCE, EEX).
"""
from decimal import Decimal
from typing import List, Optional
from .base import BaseCommodityCatalogProvider, RawCommoditySpec, RawExchangeListingSpec


class StaticCommodityCatalogProvider(BaseCommodityCatalogProvider):
    """
    Default deterministic static provider supplying canonical commodity reference data.
    Ensures 100% offline capability, zero vendor API dependencies, and deterministic test fixtures.
    """

    def get_commodities(self) -> List[RawCommoditySpec]:
        return self._catalog()

    def get_commodity(self, code: str) -> Optional[RawCommoditySpec]:
        for item in self._catalog():
            if item.code.upper() == code.upper():
                return item
        return None

    def _catalog(self) -> List[RawCommoditySpec]:
        return [
            # =========================================================================
            # 1. ENERGY
            # =========================================================================
            RawCommoditySpec(
                code="CL",
                name="Light Sweet Crude Oil (WTI)",
                sector="ENERGY",
                group="CRUDE_OIL",
                primary_exchange_code="NYMEX",
                base_unit_code="BBL",
                pricing_unit_code="USD_BBL",
                standard_lot_size=Decimal("1000.0"),
                standard_lot_unit_code="BBL",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="2709.00",
                deliverable_grade_standard="Light Sweet Crude (API Gravity: 37° - 42°, Sulfur <= 0.42%)",
                quality_specifications={
                    "api_gravity_min": 37.0,
                    "api_gravity_max": 42.0,
                    "sulfur_pct_max": 0.42,
                    "bs_w_pct_max": 1.0,
                    "pour_point_max_c": -1.0,
                    "viscosity_max_cst": 3.0,
                },
                primary_delivery_hub="Cushing, Oklahoma",
                delivery_hub_details={
                    "hub_name": "Cushing Pipeline & Storage Hub",
                    "state": "OK",
                    "country": "US",
                    "interconnects": ["Enterprise", "Enbridge", "Plains All American", "Magellan"],
                    "delivery_mechanism": "F.O.B. pipeline or storage terminal",
                },
                crop_year_start_month=None,
                peak_production_months=[5, 6, 7, 8, 9, 10],
                peak_demand_months=[6, 7, 8],
                seasonality_notes="Summer US driving season increases refinery runs and crude drawdowns June through August.",
                description="Global benchmark for light sweet crude oil. Physical delivery at Cushing, Oklahoma.",
                display_order=10,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="NYMEX",
                        ticker_symbol="CL",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="BBL",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=950000,
                        typical_open_interest=1850000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="CRUDEOIL",
                        contract_size=Decimal("100.0"),
                        contract_unit_code="BBL",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=85000,
                        typical_open_interest=16000,
                        trading_currency="INR",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="BRENT",
                name="Brent Crude Oil",
                sector="ENERGY",
                group="CRUDE_OIL",
                primary_exchange_code="ICE_EU",
                base_unit_code="BBL",
                pricing_unit_code="USD_BBL",
                standard_lot_size=Decimal("1000.0"),
                standard_lot_unit_code="BBL",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="CASH",
                hs_code="2709.00",
                deliverable_grade_standard="BFOET Blend (Brent, Forties, Oseberg, Ekofisk, Troll, WTI Midland)",
                quality_specifications={
                    "api_gravity_min": 37.5,
                    "api_gravity_max": 39.5,
                    "sulfur_pct_max": 0.40,
                    "cash_settlement_index": "ICE Brent Index",
                },
                primary_delivery_hub="Sullom Voe Terminal / North Sea",
                delivery_hub_details={
                    "hub_name": "Sullom Voe / Hound Point / Sture / Tees",
                    "country": "GB",
                    "delivery_mechanism": "Cash-settled against 25-day BFOET physical cash market index",
                },
                crop_year_start_month=None,
                peak_production_months=[1, 2, 3, 4, 5, 10, 11, 12],
                peak_demand_months=[7, 8, 12, 1],
                seasonality_notes="North Sea field maintenance occurs during May-September; global refining runs peak mid-summer.",
                description="International waterborne benchmark for global sweet crude pricing (~80% of global seaborne crude trade).",
                display_order=20,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="ICE_EU",
                        ticker_symbol="B",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="BBL",
                        settlement_method="CASH",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=880000,
                        typical_open_interest=2200000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="NYMEX",
                        ticker_symbol="BZ",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="BBL",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=65000,
                        typical_open_interest=160000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="BRENTCRUDE",
                        contract_size=Decimal("100.0"),
                        contract_unit_code="BBL",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="ACTIVE",
                        typical_daily_volume=9500,
                        typical_open_interest=3200,
                        trading_currency="INR",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="NG",
                name="Henry Hub Natural Gas",
                sector="ENERGY",
                group="NATURAL_GAS",
                primary_exchange_code="NYMEX",
                base_unit_code="MMBTU",
                pricing_unit_code="USD_MMBTU",
                standard_lot_size=Decimal("10000.0"),
                standard_lot_unit_code="MMBTU",
                minimum_tick_size=Decimal("0.001"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="2711.11",
                deliverable_grade_standard="Pipeline Quality Gas (Gross heating value 950-1100 Btu/scf)",
                quality_specifications={
                    "heating_value_min_btu": 950,
                    "heating_value_max_btu": 1100,
                    "methane_pct_min": 90.0,
                    "h2s_grains_per_100scf_max": 0.25,
                    "total_sulfur_grains_max": 20.0,
                },
                primary_delivery_hub="Henry Hub, Erath, Louisiana",
                delivery_hub_details={
                    "hub_name": "Sabine Pipe Line LLC Henry Hub",
                    "state": "LA",
                    "country": "US",
                    "interconnects": ["Columbia Gulf", "Gulf South", "NGPL", "Tennessee Gas", "Texas Gas", "Transco"],
                },
                crop_year_start_month=4,
                peak_production_months=[9, 10, 11, 12, 1, 2],
                peak_demand_months=[12, 1, 2, 7, 8],
                seasonality_notes="Strong bi-modal demand: winter residential heating (Dec-Feb) and summer power cooling burn (July-Aug). Injection season April-October.",
                description="North American pricing benchmark for pipeline and LNG natural gas.",
                display_order=30,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="NYMEX",
                        ticker_symbol="NG",
                        contract_size=Decimal("10000.0"),
                        contract_unit_code="MMBTU",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=450000,
                        typical_open_interest=1300000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="NATURALGAS",
                        contract_size=Decimal("1250.0"),
                        contract_unit_code="MMBTU",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=72000,
                        typical_open_interest=28000,
                        trading_currency="INR",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="RB",
                name="RBOB Gasoline",
                sector="ENERGY",
                group="REFINED_PRODUCTS",
                primary_exchange_code="NYMEX",
                base_unit_code="BBL",
                pricing_unit_code="USC_LB",
                standard_lot_size=Decimal("1000.0"),
                standard_lot_unit_code="BBL",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("4.20"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="2710.12",
                deliverable_grade_standard="Reformulated Blendstock for Oxygenate Blending (83.5 Octane minimum)",
                quality_specifications={
                    "octane_index_min": 83.5,
                    "rvp_psi_max_summer": 9.0,
                    "rvp_psi_max_winter": 15.0,
                    "sulfur_ppm_max": 10.0,
                },
                primary_delivery_hub="New York Harbor",
                delivery_hub_details={
                    "hub_name": "New York Harbor barge/pipeline delivery",
                    "state": "NJ/NY",
                    "country": "US",
                },
                crop_year_start_month=None,
                peak_production_months=[5, 6, 7, 8],
                peak_demand_months=[5, 6, 7, 8],
                seasonality_notes="Seasonal RVP transitions: summer-grade switch in March-May creates annual price spikes before driving season.",
                description="US refined gasoline futures contract (42,000 US gallons = 1,000 barrels).",
                display_order=40,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="NYMEX",
                        ticker_symbol="RB",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="BBL",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=190000,
                        typical_open_interest=390000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="HO",
                name="Ultra Low Sulfur Diesel (Heating Oil)",
                sector="ENERGY",
                group="REFINED_PRODUCTS",
                primary_exchange_code="NYMEX",
                base_unit_code="BBL",
                pricing_unit_code="USC_LB",
                standard_lot_size=Decimal("1000.0"),
                standard_lot_unit_code="BBL",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("4.20"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="2710.19",
                deliverable_grade_standard="Ultra Low Sulfur Diesel (ULSD max 15 ppm sulfur, 40 cetane minimum)",
                quality_specifications={
                    "sulfur_ppm_max": 15.0,
                    "cetane_index_min": 40.0,
                    "flash_point_min_c": 52.0,
                },
                primary_delivery_hub="New York Harbor",
                delivery_hub_details={
                    "hub_name": "New York Harbor petroleum terminals",
                    "state": "NJ/NY",
                    "country": "US",
                },
                crop_year_start_month=None,
                peak_production_months=[10, 11, 12, 1, 2],
                peak_demand_months=[11, 12, 1, 2],
                seasonality_notes="Winter space heating demand in US Northeast combines with agricultural harvesting diesel use in autumn.",
                description="Benchmark for distillates, trucking diesel, and residential heating oil (42,000 gal).",
                display_order=50,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="NYMEX",
                        ticker_symbol="HO",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="BBL",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=160000,
                        typical_open_interest=360000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="GO",
                name="Low Sulfur Gasoil",
                sector="ENERGY",
                group="REFINED_PRODUCTS",
                primary_exchange_code="ICE_EU",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("100.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("0.25"),
                tick_value=Decimal("25.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="2710.19",
                deliverable_grade_standard="European 10 ppm Ultra Low Sulfur Distillate",
                quality_specifications={
                    "sulfur_ppm_max": 10.0,
                    "density_min_kg_l": 0.820,
                    "density_max_kg_l": 0.845,
                    "flash_point_min_c": 55.0,
                },
                primary_delivery_hub="Amsterdam-Rotterdam-Antwerp (ARA)",
                delivery_hub_details={
                    "hub_name": "ARA Port Storage Terminals",
                    "country": "NL",
                    "delivery_mechanism": "In-tank transfer or barge delivery",
                },
                crop_year_start_month=None,
                peak_production_months=[10, 11, 12, 1, 2],
                peak_demand_months=[11, 12, 1, 2],
                seasonality_notes="European heating oil demand in winter; major maritime barge trade along Rhine waterway.",
                description="European benchmark for middle distillate fuels and road diesel (100 metric tons).",
                display_order=60,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="ICE_EU",
                        ticker_symbol="G",
                        contract_size=Decimal("100.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=230000,
                        typical_open_interest=620000,
                        trading_currency="USD",
                    ),
                ],
            ),

            # =========================================================================
            # 2. AGRICULTURE (GRAINS & OILSEEDS)
            # =========================================================================
            RawCommoditySpec(
                code="CORN",
                name="Corn No. 2 Yellow",
                sector="AGRICULTURE",
                group="GRAINS",
                primary_exchange_code="CBOT",
                base_unit_code="BU",
                pricing_unit_code="USC_BU",
                standard_lot_size=Decimal("5000.0"),
                standard_lot_unit_code="BU",
                minimum_tick_size=Decimal("0.0025"),
                tick_value=Decimal("12.50"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="1005.90",
                deliverable_grade_standard="U.S. No. 2 Yellow Corn at par (No. 1 at 1.5¢ premium, No. 3 at 2-4¢ discount)",
                quality_specifications={
                    "moisture_pct_max": 15.0,
                    "test_weight_lbs_bu_min": 54.0,
                    "broken_corn_foreign_pct_max": 3.0,
                    "total_damaged_kernels_pct_max": 5.0,
                },
                primary_delivery_hub="Chicago & Illinois Waterway Delivery Points",
                delivery_hub_details={
                    "hub_name": "Northern Illinois River & Chicago Switching District",
                    "state": "IL",
                    "country": "US",
                    "delivery_mechanism": "Warehouse shipping certificate",
                },
                crop_year_start_month=9,
                peak_production_months=[9, 10, 11],
                peak_demand_months=[10, 11, 12, 1, 2, 3],
                seasonality_notes="U.S. Corn Belt planting in April-May (weather rally window); pollination in July; harvest pressure Sept-Nov.",
                description="Global benchmark for coarse grain and animal feed. 5,000 bushels (~127 metric tons).",
                display_order=100,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="CBOT",
                        ticker_symbol="ZC",
                        contract_size=Decimal("5000.0"),
                        contract_unit_code="BU",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=360000,
                        typical_open_interest=1450000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="B3",
                        ticker_symbol="CCM",
                        contract_size=Decimal("450.0"),
                        contract_unit_code="BU",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=22000,
                        typical_open_interest=52000,
                        trading_currency="BRL",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="SOYBEANS",
                name="Soybeans No. 1/2 Yellow",
                sector="AGRICULTURE",
                group="OILSEEDS",
                primary_exchange_code="CBOT",
                base_unit_code="BU",
                pricing_unit_code="USC_BU",
                standard_lot_size=Decimal("5000.0"),
                standard_lot_unit_code="BU",
                minimum_tick_size=Decimal("0.0025"),
                tick_value=Decimal("12.50"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="1201.90",
                deliverable_grade_standard="U.S. No. 2 Yellow Soybeans at par",
                quality_specifications={
                    "moisture_pct_max": 13.0,
                    "test_weight_lbs_bu_min": 54.0,
                    "oil_content_typical_pct": 18.5,
                    "protein_content_typical_pct": 35.0,
                },
                primary_delivery_hub="Chicago & Illinois River Terminal Points",
                delivery_hub_details={
                    "hub_name": "Illinois River terminals to Mississippi River",
                    "state": "IL",
                    "country": "US",
                },
                crop_year_start_month=9,
                peak_production_months=[9, 10, 11],
                peak_demand_months=[10, 11, 12, 1, 2],
                seasonality_notes="Southern Hemisphere (Brazil/Argentina) harvest in Feb-April balances US harvest in Sept-Nov.",
                description="Global oilseed benchmark contract (5,000 bushels ~ 136 metric tons).",
                display_order=110,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="CBOT",
                        ticker_symbol="ZS",
                        contract_size=Decimal("5000.0"),
                        contract_unit_code="BU",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=290000,
                        typical_open_interest=890000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="B3",
                        ticker_symbol="SJC",
                        contract_size=Decimal("450.0"),
                        contract_unit_code="BU",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=14000,
                        typical_open_interest=28000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="DCE",
                        ticker_symbol="A",
                        contract_size=Decimal("10.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=210000,
                        typical_open_interest=420000,
                        trading_currency="CNY",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="SOYOIL",
                name="Soybean Oil",
                sector="AGRICULTURE",
                group="OILSEEDS",
                primary_exchange_code="CBOT",
                base_unit_code="LB",
                pricing_unit_code="USC_LB",
                standard_lot_size=Decimal("60000.0"),
                standard_lot_unit_code="LB",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("6.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="1507.10",
                deliverable_grade_standard="Crude Degummed Soybean Oil (Free fatty acids max 0.75%)",
                quality_specifications={
                    "free_fatty_acids_pct_max": 0.75,
                    "moisture_volatile_pct_max": 0.20,
                    "flash_point_min_c": 121.0,
                },
                primary_delivery_hub="Midwest Processing Plants (Decatur, IL)",
                delivery_hub_details={
                    "hub_name": "Central Illinois Crushing Plants",
                    "state": "IL",
                    "country": "US",
                },
                crop_year_start_month=10,
                peak_production_months=[10, 11, 12, 1],
                peak_demand_months=[11, 12, 1, 2, 6, 7],
                seasonality_notes="Crush margin dynamics link soybean oil directly to biodiesel mandates and renewable diesel demand.",
                description="Global vegetable oil and biofuel feed benchmark (60,000 lbs).",
                display_order=120,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="CBOT",
                        ticker_symbol="ZL",
                        contract_size=Decimal("60000.0"),
                        contract_unit_code="LB",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=145000,
                        typical_open_interest=520000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="WHEAT_SRW",
                name="Chicago Soft Red Winter Wheat",
                sector="AGRICULTURE",
                group="GRAINS",
                primary_exchange_code="CBOT",
                base_unit_code="BU",
                pricing_unit_code="USC_BU",
                standard_lot_size=Decimal("5000.0"),
                standard_lot_unit_code="BU",
                minimum_tick_size=Decimal("0.0025"),
                tick_value=Decimal("12.50"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="1001.99",
                deliverable_grade_standard="U.S. No. 2 Soft Red Winter Wheat at par",
                quality_specifications={
                    "test_weight_lbs_bu_min": 58.0,
                    "moisture_pct_max": 13.5,
                    "damaged_kernels_pct_max": 4.0,
                    "defects_pct_max": 3.0,
                },
                primary_delivery_hub="Chicago & Illinois River Waterway",
                delivery_hub_details={
                    "hub_name": "Chicago Switching District and St. Louis terminals",
                    "state": "IL",
                    "country": "US",
                },
                crop_year_start_month=6,
                peak_production_months=[6, 7, 8],
                peak_demand_months=[7, 8, 9, 10],
                seasonality_notes="Winter wheat harvest starts in June; spring emergence in March/April exposes crop to freeze risks.",
                description="Primary global benchmark for soft wheat used for flour, pastries, and general baking.",
                display_order=130,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="CBOT",
                        ticker_symbol="ZW",
                        contract_size=Decimal("5000.0"),
                        contract_unit_code="BU",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=125000,
                        typical_open_interest=410000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="PALM_OIL",
                name="Crude Palm Oil (FCPO)",
                sector="AGRICULTURE",
                group="OILSEEDS",
                primary_exchange_code="BMD",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("25.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("1.00"),
                tick_value=Decimal("25.00"),
                tick_currency="MYR",
                settlement_method="PHYSICAL",
                hs_code="1511.10",
                deliverable_grade_standard="Crude Palm Oil in bulk (Free fatty acids max 5.0%, moisture max 0.25%)",
                quality_specifications={
                    "free_fatty_acids_pct_max": 5.0,
                    "moisture_pct_max": 0.25,
                    "dobi_value_min": 2.31,
                },
                primary_delivery_hub="Port Klang & Pasir Gudang, Malaysia",
                delivery_hub_details={
                    "hub_name": "Approved Port Installations at Port Klang, Penang, Pasir Gudang",
                    "country": "MY",
                    "delivery_mechanism": "F.O.B. vessel or storage tank warrant",
                },
                crop_year_start_month=1,
                peak_production_months=[8, 9, 10, 11],
                peak_demand_months=[4, 5, 10, 11],
                seasonality_notes="Southeast Asian production follows monsoon cycle: lower output Jan-March, peak production Sept-Nov.",
                description="World benchmark for edible oils and tropical fats, setting pricing for global food and oleochemical markets.",
                display_order=140,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="BMD",
                        ticker_symbol="FCPO",
                        contract_size=Decimal("25.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=85000,
                        typical_open_interest=240000,
                        trading_currency="MYR",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="DCE",
                        ticker_symbol="P",
                        contract_size=Decimal("10.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=380000,
                        typical_open_interest=480000,
                        trading_currency="CNY",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="CPO",
                        contract_size=Decimal("10.0"),
                        contract_unit_code="MT",
                        settlement_method="CASH",
                        is_primary_benchmark=False,
                        liquidity_tier="ACTIVE",
                        typical_daily_volume=16000,
                        typical_open_interest=9000,
                        trading_currency="INR",
                    ),
                ],
            ),

            # =========================================================================
            # 3. SOFTS (COFFEE, SUGAR, COCOA, COTTON)
            # =========================================================================
            RawCommoditySpec(
                code="COFFEE_ARABICA",
                name="Coffee 'C' (Arabica)",
                sector="AGRICULTURE",
                group="SOFTS",
                primary_exchange_code="ICE_US",
                base_unit_code="LB",
                pricing_unit_code="USC_LB",
                standard_lot_size=Decimal("37500.0"),
                standard_lot_unit_code="LB",
                minimum_tick_size=Decimal("0.0005"),
                tick_value=Decimal("18.75"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="0901.11",
                deliverable_grade_standard="Washed Arabica Coffee from 20 approved origins (Brazil, Colombia, etc.)",
                quality_specifications={
                    "screen_size_typical": "14/15/16",
                    "defects_count_max": 15,
                    "cup_quality": "Clean cup, good body and acidity",
                },
                primary_delivery_hub="Port of New York / Virginia / New Orleans / Bremen / Antwerp",
                delivery_hub_details={
                    "hub_name": "Licensed Exchange Warehouses in US and European Seaports",
                    "country": "US",
                },
                crop_year_start_month=10,
                peak_production_months=[5, 6, 7, 8],
                peak_demand_months=[11, 12, 1, 2],
                seasonality_notes="Brazilian harvest occurs May-August; frost risk in Brazil during June-July is primary price driver.",
                description="Global price benchmark for high-grade Arabica coffee beans (37,500 lbs ~ 250 bags).",
                display_order=150,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="ICE_US",
                        ticker_symbol="KC",
                        contract_size=Decimal("37500.0"),
                        contract_unit_code="LB",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=48000,
                        typical_open_interest=250000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="B3",
                        ticker_symbol="ICF",
                        contract_size=Decimal("13200.0"),
                        contract_unit_code="LB",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="ACTIVE",
                        typical_daily_volume=6000,
                        typical_open_interest=19000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="SUGAR_11",
                name="Sugar No. 11 (Raw Centrifugal)",
                sector="AGRICULTURE",
                group="SOFTS",
                primary_exchange_code="ICE_US",
                base_unit_code="LB",
                pricing_unit_code="USC_LB",
                standard_lot_size=Decimal("112000.0"),
                standard_lot_unit_code="LB",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("11.20"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="1701.14",
                deliverable_grade_standard="Raw centrifugal cane sugar of 96 degrees polarization",
                quality_specifications={
                    "polarization_base_deg": 96.0,
                    "polarization_min_deg": 94.0,
                    "color_icumsa_max": 1200,
                },
                primary_delivery_hub="Santos / Paranagua, Brazil (and Caribbean ports)",
                delivery_hub_details={
                    "hub_name": "Port of Santos terminals and international load ports",
                    "country": "BR",
                    "delivery_mechanism": "F.O.B. vessel in country of origin",
                },
                crop_year_start_month=10,
                peak_production_months=[5, 6, 7, 8, 9, 10],
                peak_demand_months=[7, 8, 9, 10, 11],
                seasonality_notes="Center-South Brazil sugarcane harvest runs April-November; Indian and Thai monsoon drives winter crushing.",
                description="Global benchmark for physical raw sugar trade (112,000 lbs = 50 long tons).",
                display_order=160,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="ICE_US",
                        ticker_symbol="SB",
                        contract_size=Decimal("112000.0"),
                        contract_unit_code="LB",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=140000,
                        typical_open_interest=880000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="COCOA",
                name="Cocoa",
                sector="AGRICULTURE",
                group="SOFTS",
                primary_exchange_code="ICE_US",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("10.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("1.00"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="1801.00",
                deliverable_grade_standard="Fermented Cocoa Beans of merchantable quality",
                quality_specifications={
                    "bean_count_per_100g_max": 100,
                    "defective_beans_pct_max": 10.0,
                    "moisture_pct_max": 8.0,
                },
                primary_delivery_hub="Port of New York / Delaware River Ports",
                delivery_hub_details={
                    "hub_name": "Licensed warehouses in New York and Delaware River",
                    "country": "US",
                },
                crop_year_start_month=10,
                peak_production_months=[10, 11, 12, 1, 2],
                peak_demand_months=[11, 12, 1, 2],
                seasonality_notes="West African main crop (Ivory Coast / Ghana ~60% of world supply) harvested Oct-Jan; mid-crop May-July.",
                description="World benchmark for cocoa confectionery industry (10 metric tons).",
                display_order=170,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="ICE_US",
                        ticker_symbol="CC",
                        contract_size=Decimal("10.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=38000,
                        typical_open_interest=190000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="ICE_EU",
                        ticker_symbol="C",
                        contract_size=Decimal("10.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=42000,
                        typical_open_interest=220000,
                        trading_currency="GBP",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="COTTON_2",
                name="Cotton No. 2",
                sector="AGRICULTURE",
                group="SOFTS",
                primary_exchange_code="ICE_US",
                base_unit_code="LB",
                pricing_unit_code="USC_LB",
                standard_lot_size=Decimal("50000.0"),
                standard_lot_unit_code="LB",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("5.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="5201.00",
                deliverable_grade_standard="Strict Low Middling (Color 41, Leaf 4, Staple 37 = 1-5/32 inch)",
                quality_specifications={
                    "staple_length_min_inches": "1-2/32",
                    "micronaire_min": 3.5,
                    "micronaire_max": 4.9,
                    "strength_grams_tex_min": 25.0,
                },
                primary_delivery_hub="Approved Warehouses in Galveston, Houston, Dallas, Memphis",
                delivery_hub_details={
                    "hub_name": "US Cotton Belt Delivery Warehouses",
                    "country": "US",
                },
                crop_year_start_month=8,
                peak_production_months=[9, 10, 11, 12],
                peak_demand_months=[10, 11, 12, 1, 2],
                seasonality_notes="Northern Hemisphere harvest runs Sept-Dec; Texas weather is main supply driver.",
                description="Global textile fiber benchmark (50,000 lbs net weight ~ 100 bales).",
                display_order=180,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="ICE_US",
                        ticker_symbol="CT",
                        contract_size=Decimal("50000.0"),
                        contract_unit_code="LB",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=32000,
                        typical_open_interest=230000,
                        trading_currency="USD",
                    ),
                ],
            ),

            # =========================================================================
            # 4. PRECIOUS METALS
            # =========================================================================
            RawCommoditySpec(
                code="GOLD",
                name="Gold (100 Troy Ounces)",
                sector="METALS_PRECIOUS",
                group="PRECIOUS_METALS",
                primary_exchange_code="COMEX",
                base_unit_code="TOZ",
                pricing_unit_code="USD_TOZ",
                standard_lot_size=Decimal("100.0"),
                standard_lot_unit_code="TOZ",
                minimum_tick_size=Decimal("0.10"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="7108.12",
                deliverable_grade_standard="Fine gold bar (minimum 0.995 fineness = 99.5% pure gold)",
                quality_specifications={
                    "fineness_min": 0.995,
                    "bar_weights_allowed": ["100 oz", "1 kg (at 32.15 oz)"],
                    "approved_refiners": "LBMA / COMEX Good Delivery List",
                },
                primary_delivery_hub="Licensed Vaults in New York City",
                delivery_hub_details={
                    "hub_name": "Approved depositories in NYC metropolitan area (e.g. Brink's, HSBC, JP Morgan)",
                    "city": "New York",
                    "state": "NY",
                    "country": "US",
                    "delivery_mechanism": "Electronic warehouse depository warrant",
                },
                crop_year_start_month=None,
                peak_production_months=[],
                peak_demand_months=[9, 10, 11, 12, 1],
                seasonality_notes="Indian wedding/festival season (Diwali in Oct/Nov) and Chinese New Year (Jan/Feb) drive physical jewelry demand peaks.",
                description="Global financial and monetary reserve benchmark for precious metals.",
                display_order=200,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="COMEX",
                        ticker_symbol="GC",
                        contract_size=Decimal("100.0"),
                        contract_unit_code="TOZ",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=275000,
                        typical_open_interest=530000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="GOLD",
                        contract_size=Decimal("32.1507"),
                        contract_unit_code="TOZ",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=21000,
                        typical_open_interest=17500,
                        trading_currency="INR",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="SHFE",
                        ticker_symbol="AU",
                        contract_size=Decimal("32.1507"),
                        contract_unit_code="TOZ",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=195000,
                        typical_open_interest=260000,
                        trading_currency="CNY",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="SILVER",
                name="Silver (5,000 Troy Ounces)",
                sector="METALS_PRECIOUS",
                group="PRECIOUS_METALS",
                primary_exchange_code="COMEX",
                base_unit_code="TOZ",
                pricing_unit_code="USD_TOZ",
                standard_lot_size=Decimal("5000.0"),
                standard_lot_unit_code="TOZ",
                minimum_tick_size=Decimal("0.005"),
                tick_value=Decimal("25.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="7106.91",
                deliverable_grade_standard="Fine silver bar (minimum 0.999 fineness = 99.9% pure silver)",
                quality_specifications={
                    "fineness_min": 0.999,
                    "bar_sizes_allowed": ["1000 oz bars with 10% weight tolerance"],
                },
                primary_delivery_hub="Licensed Vaults in New York City",
                delivery_hub_details={
                    "hub_name": "COMEX approved vault depositories in NYC area",
                    "city": "New York",
                    "state": "NY",
                    "country": "US",
                },
                crop_year_start_month=None,
                peak_production_months=[],
                peak_demand_months=[10, 11, 12],
                seasonality_notes="Dual driver: monetary precious asset and industrial metal (solar photovoltaic cells and electronics).",
                description="Dual precious and industrial metal benchmark (5,000 troy ounces).",
                display_order=210,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="COMEX",
                        ticker_symbol="SI",
                        contract_size=Decimal("5000.0"),
                        contract_unit_code="TOZ",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=98000,
                        typical_open_interest=175000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="SILVER",
                        contract_size=Decimal("964.5"),
                        contract_unit_code="TOZ",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=24000,
                        typical_open_interest=19000,
                        trading_currency="INR",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="SHFE",
                        ticker_symbol="AG",
                        contract_size=Decimal("482.25"),
                        contract_unit_code="TOZ",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=320000,
                        typical_open_interest=470000,
                        trading_currency="CNY",
                    ),
                ],
            ),

            # =========================================================================
            # 5. BASE METALS (COPPER, ALUMINUM, ZINC, NICKEL)
            # =========================================================================
            RawCommoditySpec(
                code="COPPER",
                name="High Grade Copper Cathode",
                sector="METALS_BASE",
                group="BASE_METALS",
                primary_exchange_code="LME",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("25.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("0.50"),
                tick_value=Decimal("12.50"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="7403.11",
                deliverable_grade_standard="Grade A Copper Cathode conforming to BS EN 1978:1998 (Cu-ETP-2)",
                quality_specifications={
                    "copper_purity_min_pct": 99.9935,
                    "oxygen_ppm_max": 450,
                    "total_impurities_ppm_max": 65,
                },
                primary_delivery_hub="LME Approved Worldwide Warehouse Network",
                delivery_hub_details={
                    "hub_name": "LME licensed warehouses in Europe, Asia, and North America",
                    "country": "GB",
                    "delivery_mechanism": "LME electronic warrant transfer",
                },
                crop_year_start_month=None,
                peak_production_months=[],
                peak_demand_months=[3, 4, 5, 9, 10],
                seasonality_notes="Spring construction and manufacturing acceleration in China and Northern Hemisphere increases copper rod demand.",
                description="Global bellwether for macroeconomic growth, electrification, and renewable energy grids.",
                display_order=300,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="LME",
                        ticker_symbol="CA",
                        contract_size=Decimal("25.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=145000,
                        typical_open_interest=330000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="COMEX",
                        ticker_symbol="HG",
                        contract_size=Decimal("11.3398"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=115000,
                        typical_open_interest=270000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="SHFE",
                        ticker_symbol="CU",
                        contract_size=Decimal("5.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=230000,
                        typical_open_interest=390000,
                        trading_currency="CNY",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="MCX",
                        ticker_symbol="COPPER",
                        contract_size=Decimal("2.5"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="ACTIVE",
                        typical_daily_volume=15000,
                        typical_open_interest=8200,
                        trading_currency="INR",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="ALUMINUM",
                name="Primary High Grade Aluminum",
                sector="METALS_BASE",
                group="BASE_METALS",
                primary_exchange_code="LME",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("25.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("0.50"),
                tick_value=Decimal("12.50"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="7601.10",
                deliverable_grade_standard="Primary Aluminum ingots conforming to BS EN 576:1995 (grade Al 99.70)",
                quality_specifications={
                    "aluminum_content_min_pct": 99.70,
                    "iron_content_max_pct": 0.20,
                    "silicon_content_max_pct": 0.10,
                },
                primary_delivery_hub="LME Approved Worldwide Warehouses",
                delivery_hub_details={
                    "hub_name": "LME licensed warehouses (Rotterdam, Antwerp, Singapore, Johor)",
                    "country": "GB",
                },
                crop_year_start_month=None,
                peak_production_months=[],
                peak_demand_months=[3, 4, 5, 9, 10],
                seasonality_notes="Automotive and aerospace production cycles drive demand; smelter energy costs (power tariffs) drive supply.",
                description="Lightweight metal benchmark for aerospace, automotive, transport, and packaging sectors (25 metric tons).",
                display_order=310,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="LME",
                        ticker_symbol="AH",
                        contract_size=Decimal("25.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=165000,
                        typical_open_interest=680000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="SHFE",
                        ticker_symbol="AL",
                        contract_size=Decimal("5.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=290000,
                        typical_open_interest=440000,
                        trading_currency="CNY",
                    ),
                ],
            ),

            # =========================================================================
            # 6. LIVESTOCK
            # =========================================================================
            RawCommoditySpec(
                code="LIVE_CATTLE",
                name="Live Cattle",
                sector="LIVESTOCK",
                group="LIVESTOCK",
                primary_exchange_code="CME",
                base_unit_code="LB",
                pricing_unit_code="USD_CWT",
                standard_lot_size=Decimal("40000.0"),
                standard_lot_unit_code="LB",
                minimum_tick_size=Decimal("0.00025"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="PHYSICAL",
                hs_code="0102.29",
                deliverable_grade_standard="55% Choice, 45% Select Quality Grade fed steers (1,050 to 1,500 lbs)",
                quality_specifications={
                    "steer_weight_min_lbs": 1050,
                    "steer_weight_max_lbs": 1500,
                    "estimated_dressing_pct": 63.0,
                    "usda_quality_grade": "Choice / Select",
                },
                primary_delivery_hub="Approved Livestock Yards (Nebraska, Kansas, Texas, Colorado)",
                delivery_hub_details={
                    "hub_name": "CME-approved livestock delivery points in Plains states",
                    "country": "US",
                },
                crop_year_start_month=1,
                peak_production_months=[4, 5, 9, 10],
                peak_demand_months=[5, 6, 7],
                seasonality_notes="Summer outdoor grilling season (Memorial Day through Labor Day) drives peak beef cut-out values.",
                description="Global benchmark for fed beef cattle futures (40,000 lbs = 400 cwt).",
                display_order=400,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="CME",
                        ticker_symbol="LE",
                        contract_size=Decimal("40000.0"),
                        contract_unit_code="LB",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=68000,
                        typical_open_interest=350000,
                        trading_currency="USD",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="LEAN_HOGS",
                name="Lean Hogs",
                sector="LIVESTOCK",
                group="LIVESTOCK",
                primary_exchange_code="CME",
                base_unit_code="LB",
                pricing_unit_code="USD_CWT",
                standard_lot_size=Decimal("40000.0"),
                standard_lot_unit_code="LB",
                minimum_tick_size=Decimal("0.00025"),
                tick_value=Decimal("10.00"),
                tick_currency="USD",
                settlement_method="CASH",
                hs_code="0203.19",
                deliverable_grade_standard="Barrows and gilts conforming to USDA Lean Hog Index specifications",
                quality_specifications={
                    "settlement_index": "CME Lean Hog Index (2-day weighted average cash price)",
                    "carcass_lean_pct_typical": 51.0,
                },
                primary_delivery_hub="Cash Index Settlement (Midwest Pork Processors)",
                delivery_hub_details={
                    "hub_name": "USDA mandatory price reporting pork packers",
                    "country": "US",
                },
                crop_year_start_month=1,
                peak_production_months=[10, 11, 12],
                peak_demand_months=[6, 7, 8],
                seasonality_notes="Summer pork demand peak meets seasonal spring weight dips; autumn slaughter runs cause seasonal lows.",
                description="Benchmark for pork meat production (40,000 lbs carcass weight).",
                display_order=410,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="CME",
                        ticker_symbol="HE",
                        contract_size=Decimal("40000.0"),
                        contract_unit_code="LB",
                        settlement_method="CASH",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=58000,
                        typical_open_interest=290000,
                        trading_currency="USD",
                    ),
                ],
            ),

            # =========================================================================
            # 7. BULK & ENVIRONMENTAL
            # =========================================================================
            RawCommoditySpec(
                code="IRON_ORE",
                name="Iron Ore 62% Fe CFR China",
                sector="FREIGHT_BULK",
                group="BULK_FREIGHT",
                primary_exchange_code="SGX",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("100.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("1.00"),
                tick_currency="USD",
                settlement_method="CASH",
                hs_code="2601.11",
                deliverable_grade_standard="Standard Iron Ore Fines with 62% Iron (Fe) content delivered CFR Qingdao",
                quality_specifications={
                    "fe_content_pct": 62.0,
                    "silica_pct_max": 4.5,
                    "alumina_pct_max": 2.5,
                    "phosphorus_pct_max": 0.075,
                    "moisture_pct_max": 8.0,
                },
                primary_delivery_hub="Qingdao / Caofeidian Port, China",
                delivery_hub_details={
                    "hub_name": "Qingdao port delivery CFR China",
                    "country": "CN",
                    "delivery_mechanism": "Cash settlement against TSI Iron Ore CFR China Index",
                },
                crop_year_start_month=None,
                peak_production_months=[],
                peak_demand_months=[3, 4, 5, 9, 10],
                seasonality_notes="Spring construction resumption in China drives steel mill blast furnace restocking.",
                description="International price benchmark for seaborne dry bulk iron ore steelmaking feed.",
                display_order=500,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="SGX",
                        ticker_symbol="FEF",
                        contract_size=Decimal("100.0"),
                        contract_unit_code="MT",
                        settlement_method="CASH",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=115000,
                        typical_open_interest=295000,
                        trading_currency="USD",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="DCE",
                        ticker_symbol="I",
                        contract_size=Decimal("100.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=460000,
                        typical_open_interest=620000,
                        trading_currency="CNY",
                    ),
                ],
            ),
            RawCommoditySpec(
                code="EUA_CARBON",
                name="European Union Carbon Allowance (EUA)",
                sector="ENVIRONMENTAL",
                group="CARBON_EMISSIONS",
                primary_exchange_code="EEX",
                base_unit_code="MT",
                pricing_unit_code="USD_MT",
                standard_lot_size=Decimal("1000.0"),
                standard_lot_unit_code="MT",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("10.00"),
                tick_currency="EUR",
                settlement_method="PHYSICAL",
                hs_code="3825.90",
                deliverable_grade_standard="European Union Allowance (EUA) conforming to Directive 2003/87/EC",
                quality_specifications={
                    "unit_definition": "1 metric ton of carbon dioxide equivalent (tCO2e)",
                    "registry": "European Union Registry (Union Registry)",
                },
                primary_delivery_hub="Union Registry (European Commission)",
                delivery_hub_details={
                    "hub_name": "Electronic EU Union Registry account",
                    "country": "DE",
                    "delivery_mechanism": "Electronic transfer of allowance compliance units",
                },
                crop_year_start_month=None,
                peak_production_months=[],
                peak_demand_months=[3, 4, 11, 12],
                seasonality_notes="Compliance deadline annually on April 30 drives surge in spot and futures demand in March/April.",
                description="Global benchmark for compliance carbon emissions allowances under EU Emissions Trading System (EU ETS).",
                display_order=510,
                listings=[
                    RawExchangeListingSpec(
                        exchange_code="EEX",
                        ticker_symbol="FEUA",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=True,
                        liquidity_tier="BENCHMARK",
                        typical_daily_volume=48000,
                        typical_open_interest=780000,
                        trading_currency="EUR",
                    ),
                    RawExchangeListingSpec(
                        exchange_code="ICE_EU",
                        ticker_symbol="C",
                        contract_size=Decimal("1000.0"),
                        contract_unit_code="MT",
                        settlement_method="PHYSICAL",
                        is_primary_benchmark=False,
                        liquidity_tier="HIGH",
                        typical_daily_volume=41000,
                        typical_open_interest=650000,
                        trading_currency="EUR",
                    ),
                ],
            ),
        ]
