# Generated by Django 5.2.17 on 2026-09-19 07:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text="Standard frequency code (e.g. 'TICK', '1M', 'DAILY', 'WEEKLY', 'EVENT_DRIVEN')", max_length=32, unique=True)),
                ('name', models.CharField(help_text='Human-readable frequency name', max_length=128)),
                ('standard_interval_seconds', models.PositiveIntegerField(blank=True, help_text='Nominal interval duration in seconds (null for irregular/event-driven)', null=True)),
                ('is_regular', models.BooleanField(default=True, help_text='True for scheduled regular intervals; False for ad-hoc or event-driven releases')),
                ('description', models.TextField(blank=True, default='', help_text="Operational cadence details (e.g. 'Released every Wednesday at 10:30 AM EST')")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if this frequency is currently supported')),
            ],
            options={
                'verbose_name': 'Observation Frequency',
                'verbose_name_plural': 'Observation Frequencies',
                'ordering': ['standard_interval_seconds', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text="Canonical unit code (e.g. 'BBL', 'MT', 'BU', 'MMBTU', 'USD_BBL')", max_length=32, unique=True)),
                ('name', models.CharField(help_text="Full name (e.g. 'Barrels', 'Metric Tons', 'Bushels')", max_length=128)),
                ('symbol', models.CharField(blank=True, default='', help_text="Abbreviated symbol or display glyph (e.g. 'bbl', 't', 'bu', '$')", max_length=16)),
                ('unit_type', models.CharField(choices=[('VOLUME', 'Volume'), ('MASS', 'Mass / Weight'), ('ENERGY', 'Energy'), ('CURRENCY', 'Currency'), ('PRICE_PER_UNIT', 'Price per Unit'), ('RATIO', 'Ratio / Spread / Percentage'), ('INDEX', 'Index Points'), ('COUNT', 'Count / Head / Vessel'), ('TEMPERATURE', 'Temperature / Degree Days')], db_index=True, help_text='Dimensional type of unit', max_length=32)),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=Decimal('1.0'), help_text='Multiplier to convert this unit into its base_unit (value * factor = base_value)', max_digits=18)),
                ('description', models.TextField(blank=True, default='', help_text='Contextual notes on unit specifications or regional conventions')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if this unit is active')),
                ('base_unit', models.ForeignKey(blank=True, help_text='Reference base unit for standard mathematical conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='metadata.unitmaster')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['unit_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DataDomainMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text="Machine-readable canonical identifier (e.g. 'FUTURES_CURVES', 'INVENTORIES')", max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable title for the domain', max_length=128)),
                ('category', models.CharField(choices=[('MARKET', 'Financial & Exchange Market'), ('PHYSICAL', 'Physical & Supply Chain'), ('MACRO', 'Macroeconomic & Policy'), ('WEATHER', 'Weather & Climate'), ('QUALITATIVE', 'News, Events & Documents'), ('DERIVED', 'Quant, Narratives & Strategy')], db_index=True, default='MARKET', help_text='High-level category grouping', max_length=32)),
                ('description', models.TextField(blank=True, default='', help_text='Scope, definitions, and domain boundaries')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Sorting order in user interfaces and reports')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if this domain is active in the platform')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent domain if part of a sub-domain hierarchy (e.g. Fundamentals -> Inventory)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdomains', to='metadata.datadomainmaster')),
            ],
            options={
                'verbose_name': 'Data Domain',
                'verbose_name_plural': 'Data Domains',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='metadata_da_categor_e7a109_idx')],
            },
        ),
    ]
