# Generated by Django 5.2.17 on 2026-09-26 11:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('discovery_type', models.CharField(choices=[('REGIME_CHANGE', 'Market Regime Transition'), ('DIVERGENCE_ALERT', 'Cross-Domain Divergence Alert'), ('ANOMALY', 'Statistical Price/Volume/Spread Anomaly'), ('COINTEGRATION_PAIR', 'Cointegration & Mean-Reverting Spread'), ('SEASONAL_TENDENCY', 'Directional Seasonal Window'), ('VOLATILITY_PEAK', 'Forward Volatility Peak Window'), ('SPREAD_DISLOCATION', 'Processing Spread Dislocation')], db_index=True, help_text='Classification of quantitative discovery', max_length=32)),
                ('title', models.CharField(help_text="Canonical discovery title (e.g. 'CL-BRENT Spread Mean-Reversion Candidate')", max_length=255)),
                ('as_of_date', models.DateField(db_index=True, help_text='Market date of the discovery')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Normalized statistical confidence / correlation strength (0.0 to 1.0)')),
                ('is_statistically_significant', models.BooleanField(db_index=True, default=True, help_text='Flag indicating p-value < 0.05 or t-stat > 2.0')),
                ('p_value', models.FloatField(blank=True, help_text='Statistical significance p-value from hypothesis test', null=True)),
                ('t_statistic', models.FloatField(blank=True, help_text='Test statistic (t-stat, ADF tau, or z-score)', null=True)),
                ('sample_size', models.PositiveIntegerField(default=252, help_text='Number of historical observation bars in test sample')),
                ('lookback_window', models.CharField(default='252D', help_text="Lookback tenure (e.g. '30D', '90D', '252D', '5Y')", max_length=32)),
                ('evidence_payload', models.JSONField(default=dict, help_text='Structured discovery details (beta, half-life, z-score, regime label)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this finding is currently active and un-invalidated')),
                ('data_quality', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('STALE', 'Stale'), ('DUPLICATE', 'Duplicate'), ('SUSPECT', 'Suspect')], default='VALID', help_text='Input data quality audit state', max_length=16)),
                ('notes', models.TextField(blank=True, default='', help_text='Methodology notes, economic rationale, and invalidation criteria')),
                ('commodity', models.ForeignKey(help_text='Primary benchmark commodity analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='quant_discoveries', to='commodities.commoditymaster')),
                ('related_commodity', models.ForeignKey(blank=True, help_text='Secondary commodity in pairs/spreads (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_quant_discoveries', to='commodities.commoditymaster')),
            ],
            options={
                'ordering': ['-as_of_date', '-confidence_score'],
                'indexes': [models.Index(fields=['commodity', 'as_of_date'], name='quant_engin_commodi_e43548_idx'), models.Index(fields=['discovery_type', 'as_of_date'], name='quant_engin_discove_cc0df8_idx'), models.Index(fields=['is_active', 'is_statistically_significant'], name='quant_engin_is_acti_cb04b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidencePackageSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('as_of_date', models.DateField(db_index=True, help_text='Market date of the evidence package')),
                ('engine_version', models.CharField(default='1.0.0', help_text='Semantic version of the Quantitative Engine', max_length=32)),
                ('package_payload', models.JSONField(help_text='Complete JSON evidence package adhering to Section 5.12 Pydantic schema')),
                ('commodity', models.ForeignKey(help_text='Primary benchmark commodity', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_snapshots', to='commodities.commoditymaster')),
            ],
            options={
                'ordering': ['-as_of_date', 'commodity'],
                'indexes': [models.Index(fields=['commodity', 'as_of_date'], name='quant_engin_commodi_dbb4b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'as_of_date', 'engine_version'), name='unique_evidence_snapshot')],
            },
        ),
    ]
