"""
Static benchmark provider catalog provider.

Seeds 20 institutional global data vendors, government agencies,
PRAs, and market execution venues with realistic 12-factor auth references and rate limits.
"""

from typing import Dict, List, Optional

from .base import BaseProviderCatalogProvider, RawProviderSpec


class StaticProviderCatalogProvider(BaseProviderCatalogProvider):
    """
    Deterministic in-memory catalog provider populating 20 institutional
    data sources across energy, agriculture, metals, freight, macro, and weather.
    """

    def __init__(self) -> None:
        self._providers: Dict[str, RawProviderSpec] = {
            # 1. US Government & Public Statistical Agencies
            "EIA_GOV": RawProviderSpec(
                code="EIA_GOV",
                name="U.S. Energy Information Administration",
                description="Official U.S. energy statistics, weekly petroleum reports (WPSR), natural gas underground storage, and global drilling productivity.",
                provider_type="GOVERNMENT_PUBLIC",
                base_url="https://api.eia.gov/v2/",
                documentation_url="https://www.eia.gov/opendata/documentation.php",
                support_contact="eia-data@eia.gov",
                auth_type="API_KEY_QUERY_PARAM",
                env_var_name="EIA_API_KEY",
                auth_param_name="api_key",
                rate_limit_requests=5000,
                rate_limit_window_seconds=3600,
                backoff_seconds=60,
                target_sla_pct=99.80,
                display_order=10,
                notes="Primary source for Cushing crude inventories, Henry Hub weekly storage withdrawals, and US refinery utilization.",
            ),
            "USDA_FAS": RawProviderSpec(
                code="USDA_FAS",
                name="USDA Foreign Agricultural Service",
                description="World Agricultural Supply and Demand Estimates (WASDE) and Production, Supply & Distribution (PSD) global grain/oilseed balances.",
                provider_type="GOVERNMENT_PUBLIC",
                base_url="https://apps.fas.usda.gov/opendata/api/",
                documentation_url="https://apps.fas.usda.gov/opendataweb/home",
                support_contact="fas.opendata@usda.gov",
                auth_type="API_KEY_HEADER",
                env_var_name="USDA_API_KEY",
                auth_param_name="API_KEY",
                rate_limit_requests=120,
                rate_limit_window_seconds=60,
                backoff_seconds=30,
                target_sla_pct=99.50,
                display_order=20,
                notes="Monthly WASDE release published at 12:00 PM ET on scheduled release calendar.",
            ),
            "USDA_NASS": RawProviderSpec(
                code="USDA_NASS",
                name="USDA National Agricultural Statistics Service",
                description="U.S. domestic crop progress, planted acreage, yield forecasts, and grain stocks surveys.",
                provider_type="GOVERNMENT_PUBLIC",
                base_url="https://quickstats.nass.usda.gov/api/",
                documentation_url="https://quickstats.nass.usda.gov/api",
                support_contact="nass@usda.gov",
                auth_type="API_KEY_QUERY_PARAM",
                env_var_name="USDA_NASS_API_KEY",
                auth_param_name="key",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=30,
                target_sla_pct=99.50,
                display_order=30,
            ),
            "CFTC_GOV": RawProviderSpec(
                code="CFTC_GOV",
                name="U.S. Commodity Futures Trading Commission",
                description="Weekly Commitments of Traders (COT) Disaggregated and Legacy reports detailing commercial hedger vs non-commercial speculative positioning.",
                provider_type="GOVERNMENT_PUBLIC",
                base_url="https://publicreporting.cftc.gov/resource/",
                documentation_url="https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm",
                support_contact="questions@cftc.gov",
                auth_type="NONE_PUBLIC",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=30,
                target_sla_pct=99.70,
                display_order=40,
                notes="Published weekly on Fridays at 3:30 PM ET reflecting Tuesday cutoff positions.",
            ),
            "FRED_FED": RawProviderSpec(
                code="FRED_FED",
                name="Federal Reserve Bank of St. Louis (FRED)",
                description="Comprehensive macroeconomic database covering interest rates (10Y Treasury, SOFR), US Dollar Index (DXY), CPI, and money supply.",
                provider_type="GOVERNMENT_PUBLIC",
                base_url="https://api.stlouisfed.org/fred/",
                documentation_url="https://fred.stlouisfed.org/docs/api/fred/",
                support_contact="fred@stls.frb.org",
                auth_type="API_KEY_QUERY_PARAM",
                env_var_name="FRED_API_KEY",
                auth_param_name="api_key",
                rate_limit_requests=120,
                rate_limit_window_seconds=60,
                backoff_seconds=30,
                target_sla_pct=99.90,
                display_order=50,
            ),
            "NOAA_NWS": RawProviderSpec(
                code="NOAA_NWS",
                name="National Oceanic and Atmospheric Administration",
                description="U.S. and global weather observations, GFS weather models, Heating Degree Days (HDD), and Cooling Degree Days (CDD) for energy demand modeling.",
                provider_type="GOVERNMENT_PUBLIC",
                base_url="https://api.weather.gov/",
                documentation_url="https://www.weather.gov/documentation/services-web-api",
                support_contact="nws.issue@noaa.gov",
                auth_type="NONE_PUBLIC",
                rate_limit_requests=30,
                rate_limit_window_seconds=60,
                backoff_seconds=30,
                target_sla_pct=99.80,
                display_order=60,
            ),

            # 2. Derivative & Physical Exchange Direct Data Services
            "CME_DATAMINE": RawProviderSpec(
                code="CME_DATAMINE",
                name="CME Group Datamine",
                description="Official institutional market data service for NYMEX, COMEX, CBOT, and CME futures, options, and end-of-day settlement curves.",
                provider_type="EXCHANGE_DIRECT",
                base_url="https://datamine.cmegroup.com/api/v1/",
                documentation_url="https://www.cmegroup.com/market-data/datamine-api.html",
                support_contact="dataminesupport@cmegroup.com",
                auth_type="OAUTH2_CLIENT_CREDENTIALS",
                env_var_name="CME_DATAMINE_CLIENT_SECRET",
                auth_param_name="Authorization",
                rate_limit_requests=100,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.95,
                fallback_code="ICE_DATA_SERVICES",
                display_order=70,
                notes="Primary benchmark settlement provider for WTI (CL), Henry Hub (NG), Corn (ZC), and Gold (GC).",
            ),
            "ICE_DATA_SERVICES": RawProviderSpec(
                code="ICE_DATA_SERVICES",
                name="Intercontinental Exchange Data Services",
                description="Official market data feed for ICE Futures Europe and ICE Futures US covering Brent Crude, Low Sulphur Gasoil, Sugar No. 11, and Coffee.",
                provider_type="EXCHANGE_DIRECT",
                base_url="https://data.theice.com/api/v2/",
                documentation_url="https://www.theice.com/market-data",
                support_contact="dataservices@theice.com",
                auth_type="BEARER_TOKEN",
                env_var_name="ICE_DATA_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=120,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.95,
                fallback_code="CME_DATAMINE",
                display_order=80,
            ),
            "LME_DATA": RawProviderSpec(
                code="LME_DATA",
                name="London Metal Exchange Market Data",
                description="Daily official cash and 3-month seller settlements, warehouse stock warrants, and canceled warrants for LME Copper, Aluminium, and Nickel.",
                provider_type="EXCHANGE_DIRECT",
                base_url="https://data.lme.com/api/v1/",
                documentation_url="https://www.lme.com/Market-data",
                support_contact="marketdata@lme.com",
                auth_type="BEARER_TOKEN",
                env_var_name="LME_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.90,
                display_order=90,
            ),
            "EEX_DATA": RawProviderSpec(
                code="EEX_DATA",
                name="European Energy Exchange Data Feed",
                description="European wholesale power, TTF Natural Gas, and EU Emissions Allowances (EUA) spot and derivatives settlement prices.",
                provider_type="EXCHANGE_DIRECT",
                base_url="https://www.eex.com/api/v1/",
                documentation_url="https://www.eex.com/en/market-data",
                support_contact="marketdata@eex.com",
                auth_type="BEARER_TOKEN",
                env_var_name="EEX_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.85,
                display_order=100,
            ),
            "MCX_INDIA": RawProviderSpec(
                code="MCX_INDIA",
                name="Multi Commodity Exchange of India Data",
                description="Leading Indian commodity derivatives exchange market data for Gold, Silver, Crude Oil, and Natural Gas denominated in INR.",
                provider_type="EXCHANGE_DIRECT",
                base_url="https://www.mcxindia.com/api/v1/",
                documentation_url="https://www.mcxindia.com/market-data",
                support_contact="info@mcxindia.com",
                auth_type="API_KEY_HEADER",
                env_var_name="MCX_API_KEY",
                auth_param_name="X-MCX-API-Key",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.80,
                display_order=110,
            ),
            "SHFE_INE": RawProviderSpec(
                code="SHFE_INE",
                name="Shanghai Futures Exchange & INE",
                description="Shanghai International Energy Exchange (Medium Sour Crude SC) and SHFE Copper/Rubber official settlement and warehouse inventory reports.",
                provider_type="EXCHANGE_DIRECT",
                base_url="https://www.ine.cn/api/v1/",
                documentation_url="https://www.ine.cn/en/statements/",
                support_contact="service@shfe.com.cn",
                auth_type="API_KEY_HEADER",
                env_var_name="SHFE_API_KEY",
                auth_param_name="X-INE-Key",
                rate_limit_requests=30,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.50,
                display_order=120,
            ),

            # 3. Price Reporting Agencies (PRAs)
            "ARGUS_MEDIA": RawProviderSpec(
                code="ARGUS_MEDIA",
                name="Argus Media Direct",
                description="Leading independent PRA providing physical spot assessments for WTI Midland, ASCI sour crude, European gasoil, and global fertilizer.",
                provider_type="PRICE_REPORTING_AGENCY",
                base_url="https://api.argusmedia.com/v1/",
                documentation_url="https://www.argusmedia.com/en/data-platforms/argus-direct",
                support_contact="support@argusmedia.com",
                auth_type="BEARER_TOKEN",
                env_var_name="ARGUS_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=120,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.90,
                fallback_code="SP_GLOBAL_PLATTS",
                display_order=130,
            ),
            "SP_GLOBAL_PLATTS": RawProviderSpec(
                code="SP_GLOBAL_PLATTS",
                name="S&P Global Commodity Insights (Platts)",
                description="Global benchmark price assessments including Dated Brent, Dubai/Oman crude, Platts JKM LNG, and physical refined product barge cracks.",
                provider_type="PRICE_REPORTING_AGENCY",
                base_url="https://api.spglobal.com/commodityinsights/v2/",
                documentation_url="https://developer.spglobal.com/",
                support_contact="support.ci@spglobal.com",
                auth_type="BEARER_TOKEN",
                env_var_name="PLATTS_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=120,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.90,
                fallback_code="ARGUS_MEDIA",
                display_order=140,
            ),
            "FASTMARKETS": RawProviderSpec(
                code="FASTMARKETS",
                name="Fastmarkets Metals & Forest Products",
                description="Benchmark physical assessments for lithium, cobalt, battery raw materials, ferroalloys, steel scrap, and pulp.",
                provider_type="PRICE_REPORTING_AGENCY",
                base_url="https://api.fastmarkets.com/v1/",
                documentation_url="https://www.fastmarkets.com/developer",
                support_contact="helpdesk@fastmarkets.com",
                auth_type="BEARER_TOKEN",
                env_var_name="FASTMARKETS_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.80,
                display_order=150,
            ),
            "OPIS_ENERGY": RawProviderSpec(
                code="OPIS_ENERGY",
                name="Oil Price Information Service (OPIS)",
                description="Comprehensive rack and spot pricing for refined fuels, NGLs, renewable fuel credits (RINs), and Low Carbon Fuel Standard (LCFS) credits.",
                provider_type="PRICE_REPORTING_AGENCY",
                base_url="https://api.opisnet.com/v1/",
                documentation_url="https://www.opisnet.com/products/apis/",
                support_contact="energywork@opisnet.com",
                auth_type="BEARER_TOKEN",
                env_var_name="OPIS_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.80,
                display_order=160,
            ),

            # 4. Commercial Market Data Aggregators & Alternative Data
            "BLOOMBERG": RawProviderSpec(
                code="BLOOMBERG",
                name="Bloomberg Enterprise B-PIPE / Data License",
                description="Global multi-asset enterprise market data, corporate fundamentals, OTC swap curves, and real-time tick streaming.",
                provider_type="COMMERCIAL_AGGREGATOR",
                base_url="https://api.bloomberg.com/v1/",
                documentation_url="https://www.bloomberg.com/professional/solution/data-license/",
                support_contact="datalicense@bloomberg.net",
                auth_type="OAUTH2_CLIENT_CREDENTIALS",
                env_var_name="BLOOMBERG_CLIENT_SECRET",
                auth_param_name="Authorization",
                rate_limit_requests=300,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.98,
                fallback_code="LSEG_REFINITIV",
                display_order=170,
            ),
            "LSEG_REFINITIV": RawProviderSpec(
                code="LSEG_REFINITIV",
                name="LSEG Refinitiv DataScope Select",
                description="Institutional commodity tick history, forward curves, physical trade flows, and macroeconomic indicators.",
                provider_type="COMMERCIAL_AGGREGATOR",
                base_url="https://selectapi.datascope.refinitiv.com/RestApi/v1/",
                documentation_url="https://developers.lseg.com/",
                support_contact="datascope.support@lseg.com",
                auth_type="BEARER_TOKEN",
                env_var_name="REFINITIV_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=200,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.95,
                fallback_code="BLOOMBERG",
                display_order=180,
            ),
            "KPLER": RawProviderSpec(
                code="KPLER",
                name="Kpler Physical Cargo & Vessel Intelligence",
                description="Real-time global cargo tracking, floating storage inventories, LNG trade flows, and refining throughput tracking via AIS and satellite analytics.",
                provider_type="ALTERNATIVE_DATA",
                base_url="https://api.kpler.com/v1/",
                documentation_url="https://docs.kpler.com/",
                support_contact="support@kpler.com",
                auth_type="BEARER_TOKEN",
                env_var_name="KPLER_API_TOKEN",
                auth_param_name="Authorization",
                rate_limit_requests=60,
                rate_limit_window_seconds=60,
                backoff_seconds=60,
                target_sla_pct=99.85,
                display_order=190,
            ),

            # 5. Internal Quantitative Engine
            "INTERNAL_QUANT": RawProviderSpec(
                code="INTERNAL_QUANT",
                name="Internal Commodity Quantitative Engine",
                description="Native platform algorithmic service generating forward curve cubic spline interpolations, synthetic crack/crush spreads, and seasonality baselines.",
                provider_type="INTERNAL_ENGINE",
                base_url="http://127.0.0.1:8000/api/internal/",
                documentation_url="https://nansari-0134.github.io/commodity-market-smart-analyst/",
                support_contact="quant-systems@internal.platform",
                auth_type="NONE_PUBLIC",
                rate_limit_requests=None,
                rate_limit_window_seconds=60,
                backoff_seconds=1,
                target_sla_pct=99.99,
                display_order=200,
                notes="Deterministic computational engine; zero external network dependencies.",
            ),
        }

    def get_providers(self) -> List[RawProviderSpec]:
        """Return all 20 benchmark providers sorted by display order."""
        return sorted(self._providers.values(), key=lambda p: p.display_order)

    def get_provider(self, code: str) -> Optional[RawProviderSpec]:
        """Retrieve a provider specification by unique canonical code."""
        return self._providers.get(code)
