# Generated by Django 5.2.17 on 2026-09-22 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('datasets', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text='Canonical unique metric code (e.g. EIA_CRUDE_CUSHING_STOCKS, WASDE_CORN_US_ENDING_STOCKS).', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Full institutional metric title.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Detailed methodology, scope, and measurement parameters.')),
                ('data_type', models.CharField(choices=[('DECIMAL', 'Floating Point / Decimal'), ('INTEGER', 'Integer / Count'), ('PERCENTAGE_RATIO', 'Percentage / Ratio (0-100 or 0-1)'), ('BOOLEAN', 'Binary Boolean Flag'), ('TEXT', 'Categorical / String Label')], default='DECIMAL', help_text='Underlying value data representation type.', max_length=30)),
                ('aggregation_method', models.CharField(choices=[('LAST', 'Last Observation (Stock / Snapshot / Spot / Inventory)'), ('SUM', 'Cumulative Sum (Flow / Production / Exports / Volume)'), ('AVG', 'Arithmetic Mean (Index / Rate / Temperature)'), ('MAX', 'Peak / Maximum (Capacity / High Price)'), ('MIN', 'Trough / Minimum (Low Price / Min Level)')], default='LAST', help_text='Mathematical temporal resampling logic (LAST for stocks, SUM for flows, AVG for rates).', max_length=20)),
                ('seasonal_adjustment', models.CharField(choices=[('UNADJUSTED', 'Raw / Not Seasonally Adjusted (NSA)'), ('SEASONALLY_ADJUSTED', 'Seasonally Adjusted (SA)')], default='UNADJUSTED', help_text='Seasonal adjustment status (NSA vs SA).', max_length=30)),
                ('default_transformation', models.CharField(choices=[('RAW_LEVEL', 'Raw Level Value'), ('DIFF_1D', '1-Period Difference'), ('DIFF_1W', '1-Week Difference'), ('DIFF_1M', '1-Month Difference'), ('PCT_CHANGE_1D', '1-Day Percent Change'), ('PCT_CHANGE_1W', '1-Week Percent Change'), ('PCT_CHANGE_1M', '1-Month Percent Change'), ('PCT_CHANGE_YOY', 'Year-over-Year Percent Change'), ('LOG_RETURN', 'Logarithmic Return'), ('SPREAD_DIFF', 'Crack/Crush/Calendar Spread Difference')], default='RAW_LEVEL', help_text='Default analytical transformation hint for charting and LLM narratives.', max_length=30)),
                ('is_benchmark', models.BooleanField(db_index=True, default=False, help_text='Whether this variable is a headline benchmark indicator.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this variable is actively observed and ingested.')),
                ('display_order', models.PositiveIntegerField(default=100, help_text='Sorting order in dashboards and analytical tables.')),
                ('commodity', models.ForeignKey(blank=True, help_text='Direct physical commodity anchor (null for cross-asset or macro series).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='commodities.commoditymaster')),
                ('dataset', models.ForeignKey(help_text='Parent dataset publishing or containing this variable series.', on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='datasets.datasetmaster')),
                ('domain', models.ForeignKey(help_text='Parent data domain taxonomy classification.', on_delete=django.db.models.deletion.PROTECT, related_name='variables', to='metadata.datadomainmaster')),
                ('unit', models.ForeignKey(help_text='Canonical physical or financial unit of measure (e.g. BBL, BU, MT, USD_BBL).', on_delete=django.db.models.deletion.PROTECT, related_name='variables', to='metadata.unitmaster')),
            ],
            options={
                'verbose_name': 'Variable Master',
                'verbose_name_plural': 'Variable Master Catalog',
                'db_table': 'variables_master',
                'ordering': ['display_order', 'code'],
            },
        ),
    ]
