# Generated by Django 5.2.17 on 2026-09-22 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text='Canonical unique identifier (e.g. EIA_GOV, CME_DATAMINE, ARGUS_MEDIA).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full institutional organization or vendor title.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Provider coverage, data methodology, and licensing scope.')),
                ('provider_type', models.CharField(choices=[('GOVERNMENT_PUBLIC', 'Government / Public Statistical Agency'), ('EXCHANGE_DIRECT', 'Exchange Direct Market Data'), ('PRICE_REPORTING_AGENCY', 'Price Reporting Agency (PRA)'), ('COMMERCIAL_AGGREGATOR', 'Commercial Market Data Aggregator'), ('ALTERNATIVE_DATA', 'Alternative Data & Physical Flows'), ('INTERNAL_ENGINE', 'Internal Quant Calculation Engine')], db_index=True, default='GOVERNMENT_PUBLIC', help_text='Institutional classification of the data provider.', max_length=32)),
                ('base_url', models.URLField(help_text='Root endpoint or service URL (e.g. https://api.eia.gov/v2/).', max_length=255)),
                ('documentation_url', models.URLField(blank=True, help_text='Official developer API documentation URL.', max_length=255)),
                ('support_contact', models.CharField(blank=True, help_text='Vendor technical support email or contact portal.', max_length=150)),
                ('auth_type', models.CharField(choices=[('NONE_PUBLIC', 'No Authentication (Public Open Data)'), ('API_KEY_QUERY_PARAM', 'API Key (URL Query Parameter)'), ('API_KEY_HEADER', 'API Key (HTTP Header)'), ('BEARER_TOKEN', 'Bearer Token (Authorization Header)'), ('BASIC_AUTH', 'Basic Auth (Username/Password)'), ('OAUTH2_CLIENT_CREDENTIALS', 'OAuth 2.0 (Client Credentials Grant)')], db_index=True, default='NONE_PUBLIC', help_text='Authentication protocol expected by the vendor.', max_length=32)),
                ('env_var_name', models.CharField(blank=True, help_text='Environment variable name containing the secret (e.g. EIA_API_KEY). Never stores plaintext secrets.', max_length=80)),
                ('auth_param_name', models.CharField(blank=True, help_text="Query parameter or header name (e.g. 'api_key', 'X-API-KEY').", max_length=60)),
                ('rate_limit_requests', models.PositiveIntegerField(blank=True, help_text='Maximum request budget permitted per time window (null = unmetered).', null=True)),
                ('rate_limit_window_seconds', models.PositiveIntegerField(default=60, help_text='Rate limit time window in seconds (default 60s).')),
                ('backoff_seconds', models.PositiveIntegerField(default=60, help_text='Retry backoff interval in seconds upon encountering HTTP 429.')),
                ('target_sla_pct', models.DecimalField(decimal_places=2, default=99.5, help_text='Target service level availability percentage.', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this provider is actively used in ingestion workflows.')),
                ('display_order', models.PositiveIntegerField(default=100, help_text='Display and sort priority.')),
                ('notes', models.TextField(blank=True, help_text='Operational notes or special handling instructions.')),
                ('fallback_provider', models.ForeignKey(blank=True, help_text='Secondary failover vendor if this primary provider is unavailable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_for', to='providers.providermaster')),
            ],
            options={
                'verbose_name': 'Provider Master',
                'verbose_name_plural': 'Provider Master Catalog',
                'db_table': 'providers_master',
                'ordering': ['display_order', 'code'],
            },
        ),
    ]
