# Generated by Django 5.2.17 on 2026-10-01 12:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCatalystEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('name', models.CharField(help_text='Official name of the event or report release', max_length=200)),
                ('event_type', models.CharField(choices=[('POLICY_OPEC', 'OPEC & OPEC+ Policy'), ('GOVERNMENT_WASDE', 'USDA WASDE Crop Report'), ('MACRO_CENTRAL_BANK', 'Central Bank & Interest Rates'), ('INVENTORY_EIA', 'EIA Storage & Inventories'), ('REGULATORY_CFTC', 'CFTC Regulatory & COT'), ('WEATHER_ANOMALY', 'Severe Weather & Crop Progress'), ('GEOPOLITICAL', 'Geopolitical & Supply Disruption')], db_index=True, help_text='Categorical domain of the market catalyst', max_length=32)),
                ('impact_level', models.CharField(choices=[('HIGH', 'High Impact'), ('MEDIUM', 'Medium Impact'), ('LOW', 'Low Impact')], db_index=True, default='HIGH', help_text='Estimated market volatility impact intensity', max_length=16)),
                ('scheduled_datetime_utc', models.DateTimeField(db_index=True, help_text='Exact scheduled UTC announcement or publication timestamp')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('OCCURRED', 'Occurred'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', help_text='Current execution status of the event', max_length=16)),
                ('source_agency', models.CharField(help_text="Issuing agency or organization (e.g. 'OPEC Secretariat', 'USDA WAOB', 'EIA', 'Federal Reserve')", max_length=100)),
                ('period_covered', models.CharField(blank=True, default='', help_text="Reporting period covered (e.g. 'September 2026', 'Week Ending Sep 25')", max_length=64)),
                ('consensus_expectation', models.DecimalField(blank=True, decimal_places=4, help_text='Survey median consensus expectation prior to release', max_digits=18, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=4, help_text='Officially released actual figure', max_digits=18, null=True)),
                ('prior_value', models.DecimalField(blank=True, decimal_places=4, help_text='Prior period reported figure', max_digits=18, null=True)),
                ('surprise_magnitude', models.DecimalField(blank=True, decimal_places=4, help_text='Numerical delta: Actual minus Consensus', max_digits=18, null=True)),
                ('surprise_direction', models.CharField(choices=[('BULLISH_SURPRISE', 'Bullish Surprise'), ('BEARISH_SURPRISE', 'Bearish Surprise'), ('IN_LINE', 'In-Line with Consensus'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='UNAVAILABLE', help_text='Economic market impact interpretation of the surprise delta', max_length=24)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional qualitative commentary or release context')),
                ('affected_commodities', models.ManyToManyField(blank=True, help_text='All commodities affected by this macroeconomic release', related_name='affected_catalyst_events', to='commodities.commoditymaster')),
                ('primary_commodity', models.ForeignKey(blank=True, help_text='Primary benchmark commodity most directly impacted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_catalyst_events', to='commodities.commoditymaster')),
                ('unit', models.ForeignKey(blank=True, help_text='Unit of measure for expectation/actual metrics', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.unitmaster')),
            ],
            options={
                'verbose_name': 'Market Catalyst Event',
                'verbose_name_plural': 'Market Catalyst Events',
                'ordering': ['-scheduled_datetime_utc'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('title', models.CharField(help_text='Article headline / title', max_length=300)),
                ('summary', models.TextField(help_text='Concise executive summary or introductory excerpt')),
                ('content', models.TextField(blank=True, default='', help_text='Full article text or wire transcript (optional)')),
                ('source_name', models.CharField(db_index=True, help_text="Originating publisher or news agency (e.g. 'Reuters', 'Bloomberg', 'Platts', 'USDA')", max_length=100)),
                ('source_url', models.URLField(blank=True, default='', help_text='Canonical link to the online article', max_length=500)),
                ('published_at_utc', models.DateTimeField(db_index=True, help_text='Official publication timestamp in UTC')),
                ('author', models.CharField(blank=True, default='', help_text='Byline author or editorial desk', max_length=100)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of title and published timestamp for idempotent deduplication', max_length=64, unique=True)),
                ('overall_sentiment_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Normalized directional sentiment score (-1.000 to +1.000)', max_digits=5)),
                ('overall_sentiment_label', models.CharField(choices=[('STRONG_BULLISH', 'Strong Bullish'), ('MODERATE_BULLISH', 'Moderate Bullish'), ('NEUTRAL', 'Neutral'), ('MODERATE_BEARISH', 'Moderate Bearish'), ('STRONG_BEARISH', 'Strong Bearish')], db_index=True, default='NEUTRAL', help_text='Overall categorical sentiment polarity classification', max_length=24)),
                ('confidence_score', models.DecimalField(decimal_places=3, default=Decimal('0.850'), help_text='Confidence probability of the sentiment classification (0.0 to 1.0)', max_digits=5)),
                ('is_breaking', models.BooleanField(db_index=True, default=False, help_text='Flag marking high-urgency breaking market development')),
                ('catalyst_event', models.ForeignKey(blank=True, help_text='Associated official catalyst release event if reporting on a scheduled release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='news_intel.marketcatalystevent')),
                ('primary_commodity', models.ForeignKey(blank=True, help_text='Highest-weighted primary commodity affected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_news_articles', to='commodities.commoditymaster')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at_utc'],
            },
        ),
        migrations.CreateModel(
            name='NewsCommodityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Weighted relevance of this article to this commodity (0.000 to 1.000)', max_digits=5)),
                ('is_primary', models.BooleanField(default=False, help_text='Flag indicating whether this commodity is the primary subject of the article')),
                ('commodity_sentiment', models.CharField(choices=[('STRONG_BULLISH', 'Strong Bullish'), ('MODERATE_BULLISH', 'Moderate Bullish'), ('NEUTRAL', 'Neutral'), ('MODERATE_BEARISH', 'Moderate Bearish'), ('STRONG_BEARISH', 'Strong Bearish')], default='NEUTRAL', help_text='Directional sentiment impact specific to this individual commodity', max_length=24)),
                ('commodity_sentiment_score', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Specific sentiment polarity score for this commodity (-1.000 to +1.000)', max_digits=5)),
                ('matched_keywords', models.JSONField(blank=True, default=list, help_text='Exact physical taxonomy keywords and stems that triggered the match')),
                ('article', models.ForeignKey(help_text='Parent news article', on_delete=django.db.models.deletion.CASCADE, related_name='commodity_tags', to='news_intel.newsarticle')),
                ('commodity', models.ForeignKey(help_text='Target affected physical commodity', on_delete=django.db.models.deletion.CASCADE, related_name='news_tags', to='commodities.commoditymaster')),
            ],
            options={
                'verbose_name': 'News Commodity Tag',
                'verbose_name_plural': 'News Commodity Tags',
                'unique_together': {('article', 'commodity')},
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='commodities',
            field=models.ManyToManyField(help_text='All physical commodities affected by this article', related_name='news_articles', through='news_intel.NewsCommodityTag', to='commodities.commoditymaster'),
        ),
    ]
