# Generated by Django 5.2.17 on 2026-09-19 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text="Canonical internal symbol (e.g. 'CME', 'NYMEX', 'ICE_EU', 'IFAD', 'B3', 'BMD')", max_length=32, unique=True)),
                ('name', models.CharField(help_text='Full legal/operating name of the exchange', max_length=128)),
                ('mic', models.CharField(db_index=True, help_text="ISO 10383 Market Identifier Code (e.g. 'XNYM', 'XCME', 'IFEU', 'IFAD', 'BVMF', 'XKLS')", max_length=4, unique=True)),
                ('operating_mic', models.CharField(blank=True, default='', help_text="Parent Operating MIC if different from venue MIC (e.g. 'XCME' for NYMEX/COMEX)", max_length=4)),
                ('country', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'GB', 'BR', 'MY', 'AE', 'IN', 'CN')", max_length=2)),
                ('city', models.CharField(help_text='Primary financial center / headquarters city', max_length=64)),
                ('timezone', models.CharField(help_text="IANA standard timezone (e.g. 'America/Chicago', 'America/Sao_Paulo', 'Asia/Kuala_Lumpur', 'Asia/Dubai')", max_length=64)),
                ('currency', models.CharField(default='USD', help_text="Primary quote/settlement currency ISO code (e.g. 'USD', 'BRL', 'MYR', 'EUR')", max_length=3)),
                ('tier', models.CharField(choices=[('GLOBAL_BENCHMARK', 'Global Benchmark Venue'), ('REGIONAL_PRIMARY', 'Regional Primary Exchange'), ('DOMESTIC', 'Domestic / Local Venue')], db_index=True, default='GLOBAL_BENCHMARK', help_text='Venue hierarchy classification tier', max_length=32)),
                ('website_url', models.URLField(blank=True, default='', help_text='Official exchange portal or trading calendar URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if venue is active for data ingestion and trading')),
            ],
            options={
                'verbose_name': 'Exchange Master',
                'verbose_name_plural': 'Exchange Masters',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['country', 'tier'], name='exchanges_e_country_cfbfb6_idx'), models.Index(fields=['is_active', 'code'], name='exchanges_e_is_acti_ddb91b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeTradingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('session_type', models.CharField(choices=[('ELECTRONIC', 'Electronic Trading (Globex/Web)'), ('OPEN_OUTCRY', 'Open Outcry / Floor Pit'), ('SETTLEMENT_WINDOW', 'Official Daily Settlement Window'), ('MAINTENANCE_PAUSE', 'Daily Maintenance / System Pause')], db_index=True, default='ELECTRONIC', max_length=32)),
                ('name', models.CharField(help_text="Description (e.g. 'Globex Electronic Continuous Trading')", max_length=128)),
                ('start_time_local', models.TimeField(help_text='Opening time in exchange local time')),
                ('end_time_local', models.TimeField(help_text='Closing time in exchange local time')),
                ('days_of_week', models.CharField(default='MON,TUE,WED,THU,FRI', help_text='Comma-separated active days of week', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating if this session definition is currently active')),
                ('exchange', models.ForeignKey(help_text='Associated exchange venue', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exchanges.exchangemaster')),
            ],
            options={
                'verbose_name': 'Trading Session',
                'verbose_name_plural': 'Trading Sessions',
                'ordering': ['exchange', 'start_time_local'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('date', models.DateField(db_index=True, help_text='Calendar date of closure')),
                ('name', models.CharField(help_text="Official holiday title (e.g. 'Good Friday', 'Thanksgiving', 'Carnaval')", max_length=128)),
                ('is_full_day_closure', models.BooleanField(default=True, help_text='True if exchange is completely closed; False if partial-day early close')),
                ('early_close_time_local', models.TimeField(blank=True, help_text='Early session close time in local exchange timezone (if partial-day)', null=True)),
                ('source_api', models.CharField(blank=True, default='OFFICIAL_CALENDAR', help_text="Provenance of holiday record (e.g. 'NAGER_DATE_API', 'EXCHANGE_CALENDAR', 'MANUAL')", max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('exchange', models.ForeignKey(help_text='Associated exchange venue', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='exchanges.exchangemaster')),
            ],
            options={
                'verbose_name': 'Exchange Holiday',
                'verbose_name_plural': 'Exchange Holidays',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['exchange', 'date', 'is_full_day_closure'], name='exchanges_e_exchang_a58516_idx')],
                'unique_together': {('exchange', 'date')},
            },
        ),
    ]
