# Generated by Django 5.2.17 on 2026-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeholiday',
            name='affected_product_groups',
            field=models.CharField(blank=True, default='ALL', help_text="Commodity sectors affected (e.g. 'ALL', 'ENERGY,METALS', 'AGRICULTURE', 'EVENING_SESSION_OPEN')", max_length=255),
        ),
        migrations.AddField(
            model_name='exchangeholiday',
            name='has_settlement',
            field=models.BooleanField(default=False, help_text='True if official daily settlement prices are established for this trade date'),
        ),
        migrations.AddField(
            model_name='exchangeholiday',
            name='has_trading',
            field=models.BooleanField(default=False, help_text='True if electronic matching engines operate for trading on this date'),
        ),
        migrations.AddField(
            model_name='exchangeholiday',
            name='settlement_rolled_to_next_day',
            field=models.BooleanField(default=False, help_text='True if trades executed on this date clear and settle under the next business day (e.g. CME holiday roll)'),
        ),
    ]
