# Generated by Django 5.2.17 on 2026-09-23 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text='Canonical unique identifier (e.g. EIA_PETROLEUM_SPOT_DAILY, CFTC_COT_DISAGGREGATED_FUT).', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable title describing the endpoint feed.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Operational description of endpoint data, update schedule, and query scope.')),
                ('protocol', models.CharField(choices=[('REST_HTTP', 'REST / HTTP API'), ('FTP_SFTP', 'FTP / SFTP Batch File Server'), ('WEBSOCKET', 'WebSocket Live Streaming')], db_index=True, default='REST_HTTP', help_text='Underlying transport protocol.', max_length=20)),
                ('http_method', models.CharField(choices=[('GET', 'HTTP GET'), ('POST', 'HTTP POST')], default='GET', help_text='HTTP request method.', max_length=10)),
                ('path_template', models.CharField(help_text="Relative route or path template appended to provider base_url (e.g. 'petroleum/pri/spt/data/').", max_length=500)),
                ('response_format', models.CharField(choices=[('JSON', 'JSON Object/Array'), ('CSV', 'Comma-Separated Values (CSV)'), ('TSV', 'Tab-Separated Values (TSV)'), ('XML', 'XML Document'), ('ZIP', 'Compressed ZIP Archive'), ('PARQUET', 'Apache Parquet Columnar'), ('EXCEL_XLSX', 'Microsoft Excel (.xlsx)')], db_index=True, default='JSON', help_text='Data serialization format returned by this endpoint.', max_length=20)),
                ('data_envelope_path', models.CharField(blank=True, default='', help_text="Dot-separated path or JSON key to records array (e.g. 'response.data', 'observations', or blank for root array).", max_length=100)),
                ('default_params', models.JSONField(blank=True, default=dict, help_text="Default query parameters and pagination keys (e.g. {'frequency': 'weekly', 'length': 5000}).")),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text="Custom HTTP request headers (e.g. {'Accept': 'application/json'}).")),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=3600, help_text='Ingestion cache lifetime in seconds (default 3600 = 1 hour).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating whether endpoint is active for automated ingestion runs.')),
                ('is_deprecated', models.BooleanField(default=False, help_text='Flag indicating whether the vendor has deprecated this endpoint version.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes, migration history, or vendor quirks.')),
                ('dataset', models.ForeignKey(blank=True, help_text='Target canonical dataset populated by this endpoint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='datasets.datasetmaster')),
                ('provider', models.ForeignKey(help_text='Data vendor providing this API endpoint.', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='providers.providermaster')),
            ],
            options={
                'verbose_name': 'Endpoint Master',
                'verbose_name_plural': 'Endpoint Masters',
                'ordering': ['provider__code', 'code'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='endpoints_e_provide_8a2ace_idx'), models.Index(fields=['dataset', 'is_active'], name='endpoints_e_dataset_7d7e4a_idx'), models.Index(fields=['response_format'], name='endpoints_e_respons_dc3872_idx')],
            },
        ),
    ]
