# Generated by Django 5.2.17 on 2026-09-24 07:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
        ('contracts', '0001_initial'),
        ('endpoints', '0001_initial'),
        ('metadata', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentOfTradersObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('observation_date', models.DateField(db_index=True, help_text='CFTC survey Tuesday cutoff date')),
                ('report_type', models.CharField(choices=[('DISAGGREGATED', 'Disaggregated (Commodities)'), ('LEGACY', 'Legacy COT (Commercial vs Non-Commercial)'), ('FINANCIAL', 'Traders in Financial Futures (TFF)')], db_index=True, default='DISAGGREGATED', help_text='COT report classification', max_length=20)),
                ('open_interest', models.BigIntegerField(help_text='Total reportable open interest')),
                ('prod_merc_long', models.BigIntegerField(blank=True, help_text='Producer/Merchant/Processor/User Long contracts', null=True)),
                ('prod_merc_short', models.BigIntegerField(blank=True, help_text='Producer/Merchant/Processor/User Short contracts', null=True)),
                ('swap_long', models.BigIntegerField(blank=True, help_text='Swap Dealers Long contracts', null=True)),
                ('swap_short', models.BigIntegerField(blank=True, help_text='Swap Dealers Short contracts', null=True)),
                ('swap_spread', models.BigIntegerField(blank=True, help_text='Swap Dealers Spreading contracts', null=True)),
                ('money_manager_long', models.BigIntegerField(blank=True, help_text='Managed Money (Hedge Funds / CTAs) Long contracts', null=True)),
                ('money_manager_short', models.BigIntegerField(blank=True, help_text='Managed Money (Hedge Funds / CTAs) Short contracts', null=True)),
                ('money_manager_spread', models.BigIntegerField(blank=True, help_text='Managed Money Spreading contracts', null=True)),
                ('other_rept_long', models.BigIntegerField(blank=True, help_text='Other Reportables Long contracts', null=True)),
                ('other_rept_short', models.BigIntegerField(blank=True, help_text='Other Reportables Short contracts', null=True)),
                ('non_rept_long', models.BigIntegerField(blank=True, help_text='Non-Reportable (Small Retail Traders) Long contracts', null=True)),
                ('non_rept_short', models.BigIntegerField(blank=True, help_text='Non-Reportable (Small Retail Traders) Short contracts', null=True)),
                ('quality_status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('STALE', 'Stale'), ('DUPLICATE', 'Duplicate'), ('SUSPECT', 'Suspect')], db_index=True, default='VALID', help_text='Data quality flag', max_length=16)),
                ('commodity', models.ForeignKey(help_text='Underlying physical commodity', on_delete=django.db.models.deletion.CASCADE, related_name='cot_observations', to='commodities.commoditymaster')),
                ('source_endpoint', models.ForeignKey(blank=True, help_text='Originating ingestion endpoint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cot_observations', to='endpoints.endpointmaster')),
            ],
            options={
                'ordering': ['-observation_date', 'commodity'],
                'indexes': [models.Index(fields=['commodity', 'observation_date'], name='market_data_commodi_1d874a_idx'), models.Index(fields=['observation_date'], name='market_data_observa_97a78f_idx')],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'observation_date', 'report_type'), name='unique_cot_obs')],
            },
        ),
        migrations.CreateModel(
            name='FundamentalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('observation_date', models.DateField(db_index=True, help_text='Reference survey/effective date of the metric')),
                ('value', models.DecimalField(blank=True, decimal_places=6, help_text='Observed numerical value. Native SQL NULL represents NOT_AVAILABLE.', max_digits=20, null=True)),
                ('period_start', models.DateField(blank=True, help_text='Start date of the measurement survey window', null=True)),
                ('period_end', models.DateField(blank=True, help_text='End date of the measurement survey window (e.g. Friday for EIA)', null=True)),
                ('quality_status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('STALE', 'Stale'), ('DUPLICATE', 'Duplicate'), ('SUSPECT', 'Suspect')], db_index=True, default='VALID', help_text='Data quality flag', max_length=16)),
                ('is_preliminary', models.BooleanField(default=False, help_text='Preliminary estimate prior to final official revision')),
                ('revision_number', models.PositiveIntegerField(default=0, help_text='Revision sequence number (0 = initial release)')),
                ('source_endpoint', models.ForeignKey(blank=True, help_text='Originating ingestion endpoint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamental_observations', to='endpoints.endpointmaster')),
                ('unit', models.ForeignKey(blank=True, help_text='Unit of measure for the observation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamental_observations', to='metadata.unitmaster')),
                ('variable', models.ForeignKey(help_text='Standardized economic or supply/demand metric', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='variables.variablemaster')),
            ],
            options={
                'ordering': ['-observation_date', 'variable'],
                'indexes': [models.Index(fields=['variable', 'observation_date'], name='market_data_variabl_6afac3_idx'), models.Index(fields=['observation_date'], name='market_data_observa_0c3080_idx')],
                'constraints': [models.UniqueConstraint(fields=('variable', 'observation_date', 'revision_number'), name='unique_fundamental_obs')],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('delivery_month', models.CharField(blank=True, db_index=True, default='', help_text="Delivery contract month (e.g. '2026-11' or 'CLX26')", max_length=16)),
                ('is_prompt', models.BooleanField(db_index=True, default=False, help_text='Flag indicating active benchmark prompt (front-month) contract')),
                ('observation_date', models.DateField(db_index=True, help_text='Market trading / pricing date')),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, help_text='Session opening price (NULL if unobserved)', max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=6, help_text='Session high price (NULL if unobserved)', max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=6, help_text='Session low price (NULL if unobserved)', max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, help_text='Session close price (NULL if unobserved)', max_digits=18, null=True)),
                ('settlement_price', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Official exchange daily settlement price (NULL if unobserved)', max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, help_text='Total contracts traded during session (NULL if unobserved)', null=True)),
                ('open_interest', models.BigIntegerField(blank=True, help_text='Total active open contracts at session close (NULL if unobserved)', null=True)),
                ('quality_status', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('STALE', 'Stale'), ('DUPLICATE', 'Duplicate'), ('SUSPECT', 'Suspect')], db_index=True, default='VALID', help_text='Data quality flag (VALID, MISSING, STALE, SUSPECT, etc.)', max_length=16)),
                ('is_preliminary', models.BooleanField(default=False, help_text='Preliminary price flag prior to official settlement')),
                ('revision_number', models.PositiveIntegerField(default=0, help_text='Revision sequence number (0 = initial publication)')),
                ('commodity', models.ForeignKey(help_text='Canonical underlying physical commodity', on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='commodities.commoditymaster')),
                ('contract', models.ForeignKey(blank=True, help_text='Specific derivative contract specification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_observations', to='contracts.contractspecification')),
                ('source_endpoint', models.ForeignKey(blank=True, help_text='Endpoint source through which this observation was ingested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_observations', to='endpoints.endpointmaster')),
            ],
            options={
                'ordering': ['-observation_date', 'commodity', 'delivery_month'],
                'indexes': [models.Index(fields=['commodity', 'observation_date'], name='market_data_commodi_ac8581_idx'), models.Index(fields=['commodity', 'is_prompt', 'observation_date'], name='market_data_commodi_d39d4d_idx'), models.Index(fields=['observation_date', 'is_prompt'], name='market_data_observa_25c0a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'delivery_month', 'observation_date', 'revision_number'), name='unique_market_price_obs')],
            },
        ),
    ]
