# Generated by Django 5.2.17 on 2026-09-26 06:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('contracts', '0001_initial'),
        ('datasets', '0001_initial'),
        ('endpoints', '0001_initial'),
        ('market_data', '0001_initial'),
        ('metadata', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('event_type', models.CharField(choices=[('INVENTORY_RELEASE', 'Inventory & Storage Release'), ('CROP_REPORT', 'Crop & Agricultural Balance Report'), ('POLICY_DECISION', 'Policy / Quota / Central Bank Decision'), ('OUTAGE_INCIDENT', 'Refinery / Pipeline / Port Outage'), ('WEATHER_ANOMALY', 'Weather / Freeze / Drought Anomaly'), ('GEOPOLITICAL', 'Geopolitical / Sanction / Shipping Escalation')], db_index=True, default='INVENTORY_RELEASE', help_text='Classification of market catalyst event', max_length=32)),
                ('name', models.CharField(help_text="Canonical event name (e.g. 'EIA WPSR Cushing Crude Stocks')", max_length=255)),
                ('scheduled_time', models.DateTimeField(db_index=True, help_text='Official scheduled UTC release timestamp')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=6, help_text='Reported actual observation metric (NULL if unobserved)', max_digits=18, null=True)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=6, help_text='Market consensus / survey forecast (NULL if unobserved)', max_digits=18, null=True)),
                ('prior_value', models.DecimalField(blank=True, decimal_places=6, help_text='Previous period observation value', max_digits=18, null=True)),
                ('surprise', models.DecimalField(blank=True, decimal_places=6, help_text='Measured surprise: actual minus expected (NULL if unobserved)', max_digits=18, null=True)),
                ('standardized_surprise', models.DecimalField(blank=True, decimal_places=4, help_text='Standardized surprise (z-score against historical consensus errors)', max_digits=12, null=True)),
                ('data_quality', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('STALE', 'Stale'), ('DUPLICATE', 'Duplicate'), ('SUSPECT', 'Suspect')], default='VALID', help_text='Data quality audit flag', max_length=16)),
                ('notes', models.TextField(blank=True, default='', help_text='Qualitative commentary, revised release notes, or analyst remarks')),
                ('commodity', models.ForeignKey(blank=True, help_text='Primary affected commodity (optional for macro events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commodities.commoditymaster')),
                ('dataset', models.ForeignKey(blank=True, help_text='Associated benchmark dataset from catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='datasets.datasetmaster')),
                ('source', models.ForeignKey(blank=True, help_text='Originating data vendor / government agency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='providers.providermaster')),
                ('unit', models.ForeignKey(blank=True, help_text='Unit of measure for reported values', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.unitmaster')),
            ],
            options={
                'ordering': ['-scheduled_time', 'event_type'],
                'indexes': [models.Index(fields=['event_type', 'scheduled_time'], name='market_data_event_t_6d2d7c_idx'), models.Index(fields=['commodity', 'scheduled_time'], name='market_data_commodi_fe72e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='OptionsObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the real-world event occurred', null=True)),
                ('observation_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the metric/observation was recorded', null=True)),
                ('effective_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the data becomes active or in effect', null=True)),
                ('publication_time', models.DateTimeField(blank=True, db_index=True, help_text='Time when the provider/source published the data', null=True)),
                ('availability_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact point-in-time when data was accessible to the market (anti-lookahead timestamp)')),
                ('ingestion_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='System ingestion timestamp')),
                ('observation_date', models.DateField(db_index=True, help_text='Market trading / pricing date')),
                ('atm_implied_volatility', models.DecimalField(blank=True, decimal_places=4, help_text='At-The-Money (ATM) implied volatility in percent (e.g. 28.50%)', max_digits=8, null=True)),
                ('realized_volatility_30d', models.DecimalField(blank=True, decimal_places=4, help_text='30-day historical realized volatility in percent', max_digits=8, null=True)),
                ('iv_rv_spread', models.DecimalField(blank=True, decimal_places=4, help_text='Volatility risk premium: IV minus 30d Realized Volatility', max_digits=8, null=True)),
                ('skew_25d', models.DecimalField(blank=True, decimal_places=4, help_text='25-Delta Risk Reversal skew: 25d Call IV minus 25d Put IV', max_digits=8, null=True)),
                ('term_structure_slope', models.DecimalField(blank=True, decimal_places=4, help_text='Options term structure slope: Prompt IV minus 3M IV', max_digits=8, null=True)),
                ('put_call_volume_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Total Put volume divided by Total Call volume', max_digits=8, null=True)),
                ('put_call_oi_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Total Put Open Interest divided by Total Call Open Interest', max_digits=8, null=True)),
                ('total_options_volume', models.BigIntegerField(blank=True, help_text='Total daily options contract volume across all strikes', null=True)),
                ('total_options_oi', models.BigIntegerField(blank=True, help_text='Total options Open Interest across all strikes', null=True)),
                ('data_quality', models.CharField(choices=[('VALID', 'Valid'), ('WARNING', 'Warning'), ('INVALID', 'Invalid'), ('MISSING', 'Missing'), ('STALE', 'Stale'), ('DUPLICATE', 'Duplicate'), ('SUSPECT', 'Suspect')], default='VALID', help_text='Data quality audit flag', max_length=16)),
                ('commodity', models.ForeignKey(help_text='Canonical underlying physical commodity', on_delete=django.db.models.deletion.CASCADE, related_name='options_observations', to='commodities.commoditymaster')),
                ('contract', models.ForeignKey(blank=True, help_text='Derivative contract specification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options_observations', to='contracts.contractspecification')),
                ('source_endpoint', models.ForeignKey(blank=True, help_text='Originating ingestion endpoint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options_observations', to='endpoints.endpointmaster')),
            ],
            options={
                'ordering': ['-observation_date', 'commodity'],
                'indexes': [models.Index(fields=['commodity', 'observation_date'], name='market_data_commodi_e1a79e_idx'), models.Index(fields=['observation_date'], name='market_data_observa_df1011_idx')],
                'constraints': [models.UniqueConstraint(fields=('commodity', 'observation_date', 'contract'), name='unique_options_obs')],
            },
        ),
    ]
