# Generated by Django 5.2.17 on 2026-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('contracts', '0001_initial'),
        ('endpoints', '0001_initial'),
        ('market_data', '0002_marketevent_optionsobservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionsobservation',
            options={'ordering': ['-observation_date', 'commodity', 'delivery_month']},
        ),
        migrations.RemoveConstraint(
            model_name='optionsobservation',
            name='unique_options_obs',
        ),
        migrations.AddField(
            model_name='optionsobservation',
            name='delivery_month',
            field=models.CharField(blank=True, db_index=True, default='M1', help_text="Delivery contract month or tenor (e.g. 'M1', 'M2', ..., 'M24')", max_length=16),
        ),
        migrations.AddIndex(
            model_name='optionsobservation',
            index=models.Index(fields=['commodity', 'delivery_month', 'observation_date'], name='market_data_commodi_96c86c_idx'),
        ),
        migrations.AddConstraint(
            model_name='optionsobservation',
            constraint=models.UniqueConstraint(fields=('commodity', 'observation_date', 'contract', 'delivery_month'), name='unique_options_obs'),
        ),
    ]
