"""
Static Canonical Contract Specification Reference Provider.

Supplies institutional futures contract specifications across benchmark global derivative venues
(NYMEX, ICE, CBOT, COMEX, LME, BMD, MCX, CME, EEX).
Guarantees 100% offline capability, zero vendor API dependencies, and deterministic testing fixtures.
"""

from decimal import Decimal
from typing import List, Optional

from .base import BaseContractSpecProvider, RawContractSpec


class StaticContractSpecProvider(BaseContractSpecProvider):
    """
    Default deterministic static provider supplying canonical futures contract specifications.
    """

    def get_specifications(self) -> List[RawContractSpec]:
        return self._catalog()

    def get_specification(self, symbol_root: str, exchange_mic: str) -> Optional[RawContractSpec]:
        for spec in self._catalog():
            if spec.symbol_root.upper() == symbol_root.upper() and spec.exchange_mic.upper() == exchange_mic.upper():
                return spec
        return None

    def _catalog(self) -> List[RawContractSpec]:
        return [
            # =========================================================================
            # 1. ENERGY FUTURES
            # =========================================================================
            RawContractSpec(
                commodity_code="CL",
                exchange_mic="XNYM",
                symbol_root="CL",
                name="Light Sweet Crude Oil (WTI) Futures",
                contract_size=Decimal("1000.0"),
                contract_unit_code="BBL",
                price_quote_unit_code="USD_BBL",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="DAY_OF_PRIOR_MONTH_WITH_BUS_OFFSET",
                expiry_rule_parameter=25,
                notice_rule="First notice day is the last business day of the month preceding the delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=12,
                display_order=10,
            ),
            RawContractSpec(
                commodity_code="BRENT",
                exchange_mic="IFEU",
                symbol_root="B",
                name="Brent Crude Futures",
                contract_size=Decimal("1000.0"),
                contract_unit_code="BBL",
                price_quote_unit_code="USD_BBL",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="CASH",
                trading_months="ALL_12",
                expiry_rule="LAST_BUSINESS_DAY_OF_TWO_MONTHS_PRIOR",
                expiry_rule_parameter=0,
                notice_rule="Cash settled against the ICE Brent Index.",
                default_roll_rule="BCOM_6_TO_10_BUS_DAY",
                prompt_cycles_to_seed=12,
                display_order=20,
            ),
            RawContractSpec(
                commodity_code="NG",
                exchange_mic="XNYM",
                symbol_root="NG",
                name="Henry Hub Natural Gas Futures",
                contract_size=Decimal("10000.0"),
                contract_unit_code="MMBTU",
                price_quote_unit_code="USD_MMBTU",
                minimum_tick_size=Decimal("0.001"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="DAYS_BEFORE_MONTH_START",
                expiry_rule_parameter=3,
                notice_rule="First notice day is the first business day following the last trading day.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=12,
                display_order=30,
            ),
            RawContractSpec(
                commodity_code="RB",
                exchange_mic="XNYM",
                symbol_root="RB",
                name="RBOB Gasoline Futures",
                contract_size=Decimal("42000.0"),
                contract_unit_code="GAL",
                price_quote_unit_code="USD_BBL",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("4.20"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="LAST_BUSINESS_DAY_OF_PRIOR_MONTH",
                expiry_rule_parameter=0,
                notice_rule="First notice day is the first business day following the last trading day.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=12,
                display_order=40,
            ),
            RawContractSpec(
                commodity_code="HO",
                exchange_mic="XNYM",
                symbol_root="HO",
                name="Heating Oil / Ultra-Low Sulfur Diesel Futures",
                contract_size=Decimal("42000.0"),
                contract_unit_code="GAL",
                price_quote_unit_code="USD_BBL",
                minimum_tick_size=Decimal("0.0001"),
                tick_value=Decimal("4.20"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="LAST_BUSINESS_DAY_OF_PRIOR_MONTH",
                expiry_rule_parameter=0,
                notice_rule="First notice day is the first business day following the last trading day.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=12,
                display_order=50,
            ),
            RawContractSpec(
                commodity_code="GO",
                exchange_mic="IFEU",
                symbol_root="G",
                name="Low Sulphur Gasoil Futures",
                contract_size=Decimal("100.0"),
                contract_unit_code="MT",
                price_quote_unit_code="USD_MT",
                minimum_tick_size=Decimal("0.25"),
                tick_value=Decimal("25.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="FIFTH_BUSINESS_DAY_BEFORE_MONTH_END",
                expiry_rule_parameter=2,
                notice_rule="Physical barge/tank delivery in Antwerp-Rotterdam-Amsterdam (ARA).",
                default_roll_rule="BCOM_6_TO_10_BUS_DAY",
                prompt_cycles_to_seed=12,
                display_order=60,
            ),
            # =========================================================================
            # 2. GRAINS & OILSEEDS
            # =========================================================================
            RawContractSpec(
                commodity_code="CORN",
                exchange_mic="XCBT",
                symbol_root="ZC",
                name="Corn Futures",
                contract_size=Decimal("5000.0"),
                contract_unit_code="BU",
                price_quote_unit_code="USC_BU",
                minimum_tick_size=Decimal("0.25"),
                tick_value=Decimal("12.50"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,U,Z",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=15,
                notice_rule="First position day is the last business day of the month preceding delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=8,
                display_order=70,
            ),
            RawContractSpec(
                commodity_code="SOYBEANS",
                exchange_mic="XCBT",
                symbol_root="ZS",
                name="Soybean Futures",
                contract_size=Decimal("5000.0"),
                contract_unit_code="BU",
                price_quote_unit_code="USC_BU",
                minimum_tick_size=Decimal("0.25"),
                tick_value=Decimal("12.50"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="F,H,K,N,Q,U,X",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=15,
                notice_rule="First position day is the last business day of the month preceding delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=8,
                display_order=80,
            ),
            RawContractSpec(
                commodity_code="SOYOIL",
                exchange_mic="XCBT",
                symbol_root="ZL",
                name="Soybean Oil Futures",
                contract_size=Decimal("60000.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("6.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="F,H,K,N,Q,U,V,Z",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=15,
                notice_rule="First position day is the last business day of the month preceding delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=8,
                display_order=90,
            ),
            RawContractSpec(
                commodity_code="WHEAT_SRW",
                exchange_mic="XCBT",
                symbol_root="ZW",
                name="Chicago SRW Wheat Futures",
                contract_size=Decimal("5000.0"),
                contract_unit_code="BU",
                price_quote_unit_code="USC_BU",
                minimum_tick_size=Decimal("0.25"),
                tick_value=Decimal("12.50"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,U,Z",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=15,
                notice_rule="First position day is the last business day of the month preceding delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=8,
                display_order=100,
            ),
            RawContractSpec(
                commodity_code="PALM_OIL",
                exchange_mic="XKLS",
                symbol_root="FCPO",
                name="Crude Palm Oil Futures",
                contract_size=Decimal("25.0"),
                contract_unit_code="MT",
                price_quote_unit_code="USD_MT",
                minimum_tick_size=Decimal("1.00"),
                tick_value=Decimal("25.00"),
                trading_currency="MYR",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=15,
                notice_rule="Port Klang / Pasir Gudang storage tank receipts.",
                default_roll_rule="PROMPT_DAY_10_TO_15",
                prompt_cycles_to_seed=12,
                display_order=110,
            ),
            # =========================================================================
            # 3. SOFT COMMODITIES
            # =========================================================================
            RawContractSpec(
                commodity_code="COFFEE_ARABICA",
                exchange_mic="IFUS",
                symbol_root="KC",
                name="Coffee 'C' Futures",
                contract_size=Decimal("37500.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.05"),
                tick_value=Decimal("18.75"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,U,Z",
                expiry_rule="DAYS_BEFORE_MONTH_START",
                expiry_rule_parameter=8,
                notice_rule="Notice day is 7 business days prior to first business day of delivery month.",
                default_roll_rule="BCOM_6_TO_10_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=120,
            ),
            RawContractSpec(
                commodity_code="SUGAR_11",
                exchange_mic="IFUS",
                symbol_root="SB",
                name="Sugar No. 11 Futures",
                contract_size=Decimal("112000.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("11.20"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,V",
                expiry_rule="LAST_BUSINESS_DAY_OF_PRIOR_MONTH",
                expiry_rule_parameter=0,
                notice_rule="FOB delivery from licensed port terminals.",
                default_roll_rule="BCOM_6_TO_10_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=130,
            ),
            RawContractSpec(
                commodity_code="COCOA",
                exchange_mic="IFUS",
                symbol_root="CC",
                name="Cocoa Futures",
                contract_size=Decimal("10.0"),
                contract_unit_code="MT",
                price_quote_unit_code="USD_MT",
                minimum_tick_size=Decimal("1.00"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,U,Z",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=15,
                notice_rule="Delivery via licensed port warehouses in NY/DE/Hampton Roads.",
                default_roll_rule="BCOM_6_TO_10_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=140,
            ),
            RawContractSpec(
                commodity_code="COTTON_2",
                exchange_mic="IFUS",
                symbol_root="CT",
                name="Cotton No. 2 Futures",
                contract_size=Decimal("50000.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("5.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,V,Z",
                expiry_rule="DAYS_BEFORE_MONTH_START",
                expiry_rule_parameter=17,
                notice_rule="First notice day is 5 business days prior to first delivery day.",
                default_roll_rule="BCOM_6_TO_10_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=150,
            ),
            # =========================================================================
            # 4. PRECIOUS METALS
            # =========================================================================
            RawContractSpec(
                commodity_code="GOLD",
                exchange_mic="XCEC",
                symbol_root="GC",
                name="Gold Futures",
                contract_size=Decimal("100.0"),
                contract_unit_code="TOZ",
                price_quote_unit_code="USD_TOZ",
                minimum_tick_size=Decimal("0.10"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="G,J,M,Q,V,Z",
                expiry_rule="FIFTH_BUSINESS_DAY_BEFORE_MONTH_END",
                expiry_rule_parameter=3,
                notice_rule="Third to last business day of the delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=160,
            ),
            RawContractSpec(
                commodity_code="SILVER",
                exchange_mic="XCEC",
                symbol_root="SI",
                name="Silver Futures",
                contract_size=Decimal("5000.0"),
                contract_unit_code="TOZ",
                price_quote_unit_code="USD_TOZ",
                minimum_tick_size=Decimal("0.005"),
                tick_value=Decimal("25.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,U,Z",
                expiry_rule="FIFTH_BUSINESS_DAY_BEFORE_MONTH_END",
                expiry_rule_parameter=3,
                notice_rule="Third to last business day of the delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=170,
            ),
            # =========================================================================
            # 5. BASE METALS
            # =========================================================================
            RawContractSpec(
                commodity_code="COPPER",
                exchange_mic="XCEC",
                symbol_root="HG",
                name="High Grade Copper Futures",
                contract_size=Decimal("25000.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.05"),
                tick_value=Decimal("12.50"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,K,N,U,Z",
                expiry_rule="FIFTH_BUSINESS_DAY_BEFORE_MONTH_END",
                expiry_rule_parameter=3,
                notice_rule="Third to last business day of the delivery month.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=180,
            ),
            RawContractSpec(
                commodity_code="COPPER",
                exchange_mic="XLME",
                symbol_root="CA",
                name="LME Copper Grade A",
                contract_size=Decimal("25.0"),
                contract_unit_code="MT",
                price_quote_unit_code="USD_MT",
                minimum_tick_size=Decimal("0.50"),
                tick_value=Decimal("12.50"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="THIRD_WEDNESDAY_OF_MONTH",
                expiry_rule_parameter=0,
                notice_rule="LME daily prompt dates / Monthly Third Wednesday settlement.",
                default_roll_rule="LME_THIRD_WED_ROLL",
                prompt_cycles_to_seed=12,
                display_order=190,
            ),
            RawContractSpec(
                commodity_code="ALUMINUM",
                exchange_mic="XLME",
                symbol_root="AH",
                name="LME Primary Aluminium",
                contract_size=Decimal("25.0"),
                contract_unit_code="MT",
                price_quote_unit_code="USD_MT",
                minimum_tick_size=Decimal("0.50"),
                tick_value=Decimal("12.50"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="ALL_12",
                expiry_rule="THIRD_WEDNESDAY_OF_MONTH",
                expiry_rule_parameter=0,
                notice_rule="LME daily prompt dates / Monthly Third Wednesday settlement.",
                default_roll_rule="LME_THIRD_WED_ROLL",
                prompt_cycles_to_seed=12,
                display_order=200,
            ),
            # =========================================================================
            # 6. LIVESTOCK
            # =========================================================================
            RawContractSpec(
                commodity_code="LIVE_CATTLE",
                exchange_mic="XCME",
                symbol_root="LE",
                name="Live Cattle Futures",
                contract_size=Decimal("40000.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.025"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="G,J,M,Q,V,Z",
                expiry_rule="LAST_BUSINESS_DAY_OF_PRIOR_MONTH",
                expiry_rule_parameter=0,
                notice_rule="Physical certificate delivery via designated stockyards.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=6,
                display_order=210,
            ),
            RawContractSpec(
                commodity_code="LEAN_HOGS",
                exchange_mic="XCME",
                symbol_root="HE",
                name="Lean Hogs Futures",
                contract_size=Decimal("40000.0"),
                contract_unit_code="LB",
                price_quote_unit_code="USC_LB",
                minimum_tick_size=Decimal("0.025"),
                tick_value=Decimal("10.00"),
                trading_currency="USD",
                instrument_type="FUTURES",
                settlement_method="CASH",
                trading_months="G,J,K,M,N,Q,V,Z",
                expiry_rule="BUSINESS_DAY_BEFORE_DAY_OF_MONTH",
                expiry_rule_parameter=14,
                notice_rule="Cash settled against CME Lean Hog Index.",
                default_roll_rule="GSCI_5_TO_9_BUS_DAY",
                prompt_cycles_to_seed=8,
                display_order=220,
            ),
            # =========================================================================
            # 7. ENVIRONMENTAL / CARBON
            # =========================================================================
            RawContractSpec(
                commodity_code="EUA_CARBON",
                exchange_mic="XEEE",
                symbol_root="FEUA",
                name="EEX European Carbon Allowance (EUA) Futures",
                contract_size=Decimal("1000.0"),
                contract_unit_code="MT",
                price_quote_unit_code="USD_MT",
                minimum_tick_size=Decimal("0.01"),
                tick_value=Decimal("10.00"),
                trading_currency="EUR",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="H,M,U,Z",
                expiry_rule="DAYS_BEFORE_MONTH_START",
                expiry_rule_parameter=3,
                notice_rule="Physical transfer of EUA compliance units via Union Registry.",
                default_roll_rule="DECEMBER_ANNUAL_ROLL",
                prompt_cycles_to_seed=4,
                display_order=230,
            ),
            # =========================================================================
            # 8. MULTI-VENUE CONTRACTS (MCX INDIA BENCHMARKS)
            # =========================================================================
            RawContractSpec(
                commodity_code="CL",
                exchange_mic="XMCX",
                symbol_root="CRUDEOIL",
                name="MCX Crude Oil Futures (India)",
                contract_size=Decimal("100.0"),
                contract_unit_code="BBL",
                price_quote_unit_code="USD_BBL",
                minimum_tick_size=Decimal("1.00"),
                tick_value=Decimal("100.00"),
                trading_currency="INR",
                instrument_type="FUTURES",
                settlement_method="CASH",
                trading_months="ALL_12",
                expiry_rule="DAY_OF_PRIOR_MONTH_WITH_BUS_OFFSET",
                expiry_rule_parameter=19,
                notice_rule="Cash settled in INR against NYMEX WTI settlement converted at RBI reference rate.",
                default_roll_rule="MCX_3_DAYS_BEFORE_EXPIRY",
                prompt_cycles_to_seed=6,
                display_order=240,
            ),
            RawContractSpec(
                commodity_code="GOLD",
                exchange_mic="XMCX",
                symbol_root="GOLD",
                name="MCX Gold 1kg Futures (India)",
                contract_size=Decimal("1.0"),
                contract_unit_code="KG",
                price_quote_unit_code="USD_TOZ",
                minimum_tick_size=Decimal("1.00"),
                tick_value=Decimal("100.00"),
                trading_currency="INR",
                instrument_type="FUTURES",
                settlement_method="PHYSICAL",
                trading_months="G,J,M,Q,V,Z",
                expiry_rule="FIFTH_BUSINESS_DAY_BEFORE_MONTH_END",
                expiry_rule_parameter=5,
                notice_rule="Physical delivery in 995 fineness bars at designated Ahmedabad vaults.",
                default_roll_rule="TENDER_PERIOD_ROLL",
                prompt_cycles_to_seed=6,
                display_order=250,
            ),
        ]
