"""
Static Canonical Variable Catalog Reference Provider.

Supplies institutional benchmark variable/metric specifications across global commodity domains
(EIA, USDA, CFTC, LME, CME, Baker Hughes, NOAA, CONAB, MPOB, Federal Reserve).
Guarantees 100% offline capability, zero external vendor API dependencies, and deterministic testing fixtures.
"""

from typing import List, Optional

from .base import BaseVariableCatalogProvider, RawVariableSpec


class StaticVariableCatalogProvider(BaseVariableCatalogProvider):
    """
    Default deterministic static provider supplying canonical variable metadata.
    """

    def get_variables(self) -> List[RawVariableSpec]:
        return self._catalog()

    def get_variable(self, code: str) -> Optional[RawVariableSpec]:
        for spec in self._catalog():
            if spec.code.upper() == code.upper():
                return spec
        return None

    def _catalog(self) -> List[RawVariableSpec]:
        return [
            # =========================================================================
            # 1. ENERGY FUNDAMENTALS — EIA WEEKLY PETROLEUM STATUS (WPSR)
            # =========================================================================
            RawVariableSpec(
                code="CRUDE_CUSHING_STOCKS",
                name="Cushing Oklahoma Ending Crude Oil Stocks",
                description="Weekly ending stocks of crude oil held at the pipeline terminal and storage hub in Cushing, Oklahoma (excluding SPR).",
                dataset_code="EIA_WPSR_PETROLEUM_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MBBL",
                commodity_code="CL",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=10,
            ),
            RawVariableSpec(
                code="CRUDE_US_TOTAL_COMMERCIAL_STOCKS",
                name="US Total Commercial Crude Oil Ending Stocks",
                description="Total US commercial crude oil ending stocks excluding the Strategic Petroleum Reserve (SPR).",
                dataset_code="EIA_WPSR_PETROLEUM_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MBBL",
                commodity_code="CL",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=20,
            ),
            RawVariableSpec(
                code="CRUDE_US_SPR_STOCKS",
                name="US Strategic Petroleum Reserve (SPR) Crude Oil Stocks",
                description="Total volume of crude oil held in the US government emergency Strategic Petroleum Reserve caverns.",
                dataset_code="EIA_WPSR_PETROLEUM_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MBBL",
                commodity_code="CL",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=30,
            ),
            RawVariableSpec(
                code="GASOLINE_US_TOTAL_STOCKS",
                name="US Total Motor Gasoline Ending Inventories",
                description="Total finished and blending components motor gasoline held at refineries, bulk terminals, and pipelines.",
                dataset_code="EIA_WPSR_PETROLEUM_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MBBL",
                commodity_code="RB",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=40,
            ),
            RawVariableSpec(
                code="DISTILLATE_US_TOTAL_STOCKS",
                name="US Total Distillate Fuel Oil Inventories",
                description="Total distillate fuel oil (diesel and heating oil) stocks across all PADD refining districts.",
                dataset_code="EIA_WPSR_PETROLEUM_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MBBL",
                commodity_code="HO",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=50,
            ),
            # =========================================================================
            # 2. REFINERY UTILIZATION & RUNS
            # =========================================================================
            RawVariableSpec(
                code="US_REFINERY_UTILIZATION_PCT",
                name="US Refinery Operable Capacity Utilization Rate",
                description="Gross input to atmospheric crude oil distillation units divided by the operable distillation capacity.",
                dataset_code="EIA_WPSR_REFINERY_UTILIZATION",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="PERCENT",
                commodity_code="CL",
                data_type="DECIMAL",
                aggregation_method="AVG",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=60,
            ),
            RawVariableSpec(
                code="US_REFINERY_CRUDE_RUNS",
                name="US Refinery Gross Crude Oil Inputs",
                description="Weekly total volume of crude oil processed by US refinery distillation units.",
                dataset_code="EIA_WPSR_REFINERY_UTILIZATION",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="MBBL",
                commodity_code="CL",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=70,
            ),
            # =========================================================================
            # 3. NATURAL GAS STORAGE (EIA)
            # =========================================================================
            RawVariableSpec(
                code="NATGAS_LOWER_48_WORKING_STORAGE",
                name="US Lower 48 Natural Gas Working Underground Storage",
                description="Weekly volume of natural gas in underground storage reservoirs available for market withdrawal.",
                dataset_code="EIA_WEEKLY_NATURAL_GAS_STORAGE",
                domain_code="INVENTORIES",
                unit_code="BCF",
                commodity_code="NG",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=80,
            ),
            RawVariableSpec(
                code="NATGAS_WEEKLY_NET_CHANGE",
                name="US Natural Gas Weekly Net Storage Change",
                description="Weekly net injection (+) or withdrawal (-) into underground natural gas storage caverns.",
                dataset_code="EIA_WEEKLY_NATURAL_GAS_STORAGE",
                domain_code="INVENTORIES",
                unit_code="BCF",
                commodity_code="NG",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=True,
                display_order=90,
            ),
            # =========================================================================
            # 4. AGRICULTURAL BALANCE SHEETS — USDA WASDE
            # =========================================================================
            RawVariableSpec(
                code="WASDE_CORN_US_ENDING_STOCKS",
                name="US Corn Projected Marketing Year Ending Stocks",
                description="USDA World Agricultural Outlook Board projected carryover stocks of Corn at the end of the marketing year (August 31).",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1M",
                is_benchmark=True,
                display_order=100,
            ),
            RawVariableSpec(
                code="WASDE_CORN_US_PRODUCTION",
                name="US Corn Projected Harvest Production Volume",
                description="Total forecast harvest volume of US No. 2 Yellow Corn for the marketing year.",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=True,
                display_order=110,
            ),
            RawVariableSpec(
                code="WASDE_CORN_US_DOMESTIC_USE",
                name="US Corn Projected Total Domestic Disappearance",
                description="Total projected domestic utilization for feed, residual, ethanol, and food/industrial processing.",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=False,
                display_order=120,
            ),
            RawVariableSpec(
                code="WASDE_CORN_US_EXPORTS",
                name="US Corn Projected Total Export Shipments",
                description="Total forecasted export shipments of US Corn during the marketing crop year.",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="TRADE_FLOWS",
                unit_code="BU",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=False,
                display_order=130,
            ),
            RawVariableSpec(
                code="WASDE_SOYBEANS_US_ENDING_STOCKS",
                name="US Soybeans Projected Marketing Year Ending Stocks",
                description="USDA projected carryover stocks of Soybeans at the end of the marketing year (August 31).",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="SOYBEANS",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1M",
                is_benchmark=True,
                display_order=140,
            ),
            RawVariableSpec(
                code="WASDE_SOYBEANS_US_PRODUCTION",
                name="US Soybeans Projected Harvest Production Volume",
                description="Total forecasted harvest production volume of US Soybeans.",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="SOYBEANS",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=True,
                display_order=150,
            ),
            RawVariableSpec(
                code="WASDE_SOYBEANS_US_CRUSH",
                name="US Soybeans Domestic Processing Crush Volume",
                description="Total volume of soybeans processed domestically by crushing plants into soybean meal and soybean oil.",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="SOYBEANS",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=False,
                display_order=160,
            ),
            RawVariableSpec(
                code="WASDE_WHEAT_US_ENDING_STOCKS",
                name="US All Wheat Projected Marketing Year Ending Stocks",
                description="USDA projected carryover stocks of All Wheat at the end of the marketing year (May 31).",
                dataset_code="USDA_WASDE_WORLD_GRAINS",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="BU",
                commodity_code="WHEAT_SRW",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1M",
                is_benchmark=True,
                display_order=170,
            ),
            # =========================================================================
            # 5. AGRICULTURAL TRADE FLOWS (USDA FAS)
            # =========================================================================
            RawVariableSpec(
                code="USDA_CORN_NET_EXPORT_SALES",
                name="US Corn Weekly Net Export Sales Commitments",
                description="Weekly net new commercial export commitments reported by exporters to USDA Foreign Agricultural Service.",
                dataset_code="USDA_EXPORT_SALES_WEEKLY",
                domain_code="TRADE_FLOWS",
                unit_code="MT",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=False,
                display_order=180,
            ),
            RawVariableSpec(
                code="USDA_SOYBEANS_NET_EXPORT_SALES",
                name="US Soybeans Weekly Net Export Sales Commitments",
                description="Weekly net new commercial export commitments for soybeans reported to USDA FAS.",
                dataset_code="USDA_EXPORT_SALES_WEEKLY",
                domain_code="TRADE_FLOWS",
                unit_code="MT",
                commodity_code="SOYBEANS",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="RAW_LEVEL",
                is_benchmark=False,
                display_order=190,
            ),
            # =========================================================================
            # 6. CROP CONDITION & PROGRESS (USDA NASS)
            # =========================================================================
            RawVariableSpec(
                code="USDA_CORN_CONDITION_GOOD_EXCELLENT",
                name="US Corn Crop Rated Good or Excellent Percentage",
                description="Weekly surveyed percentage of US corn acreage evaluated in Good (G) or Excellent (EX) physiological health.",
                dataset_code="USDA_CROP_PROGRESS_WEEKLY",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="PERCENT",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="AVG",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=200,
            ),
            RawVariableSpec(
                code="USDA_SOYBEANS_CONDITION_GOOD_EXCELLENT",
                name="US Soybeans Crop Rated Good or Excellent Percentage",
                description="Weekly surveyed percentage of US soybean acreage evaluated in Good or Excellent physiological condition.",
                dataset_code="USDA_CROP_PROGRESS_WEEKLY",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="PERCENT",
                commodity_code="SOYBEANS",
                data_type="DECIMAL",
                aggregation_method="AVG",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=210,
            ),
            RawVariableSpec(
                code="USDA_CORN_PLANTING_PROGRESS",
                name="US Corn Acreage Planted Cumulative Percentage",
                description="Weekly cumulative percentage of intended corn crop acres planted in top 18 agricultural producing states.",
                dataset_code="USDA_CROP_PROGRESS_WEEKLY",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="PERCENT",
                commodity_code="CORN",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=220,
            ),
            # =========================================================================
            # 7. TRADER POSITIONING (CFTC COMMITMENTS OF TRADERS)
            # =========================================================================
            RawVariableSpec(
                code="COT_WTI_PRODUCER_MERCHANT_NET",
                name="CFTC WTI Commercial Producer / Merchant Net Position",
                description="Net open futures and delta-adjusted options contracts held by commercial physical producers, merchants, and processors.",
                dataset_code="CFTC_COT_DISAGGREGATED_FUT_OPT",
                domain_code="CFTC_COT",
                unit_code="COUNT",
                commodity_code="CL",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=230,
            ),
            RawVariableSpec(
                code="COT_WTI_MANAGED_MONEY_LONG",
                name="CFTC WTI Managed Money Gross Long Positions",
                description="Gross open long futures contracts held by registered Commodity Trading Advisors (CTAs) and hedge funds.",
                dataset_code="CFTC_COT_DISAGGREGATED_FUT_OPT",
                domain_code="CFTC_COT",
                unit_code="COUNT",
                commodity_code="CL",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=240,
            ),
            RawVariableSpec(
                code="COT_WTI_MANAGED_MONEY_SHORT",
                name="CFTC WTI Managed Money Gross Short Positions",
                description="Gross open short futures contracts held by speculative investment funds.",
                dataset_code="CFTC_COT_DISAGGREGATED_FUT_OPT",
                domain_code="CFTC_COT",
                unit_code="COUNT",
                commodity_code="CL",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=250,
            ),
            RawVariableSpec(
                code="COT_CORN_MANAGED_MONEY_NET",
                name="CFTC Corn Managed Money Speculative Net Position",
                description="Net positioning (Gross Long minus Gross Short) held by managed money funds in CBOT Corn contracts.",
                dataset_code="CFTC_COT_DISAGGREGATED_FUT_OPT",
                domain_code="CFTC_COT",
                unit_code="COUNT",
                commodity_code="CORN",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=260,
            ),
            RawVariableSpec(
                code="COT_GOLD_MANAGED_MONEY_NET",
                name="CFTC Gold Managed Money Speculative Net Position",
                description="Net long or short contracts held by speculative funds in COMEX Gold futures & options.",
                dataset_code="CFTC_COT_DISAGGREGATED_FUT_OPT",
                domain_code="CFTC_COT",
                unit_code="COUNT",
                commodity_code="GOLD",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=270,
            ),
            # =========================================================================
            # 8. METALS WAREHOUSE INVENTORIES (LME)
            # =========================================================================
            RawVariableSpec(
                code="LME_COPPER_ON_WARRANT_STOCKS",
                name="LME Copper On-Warrant Available Stocks",
                description="Physical copper ingots/cathodes held in London Metal Exchange licensed warehouses available for warrant trading.",
                dataset_code="LME_DAILY_WAREHOUSE_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MT",
                commodity_code="COPPER",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1D",
                is_benchmark=True,
                display_order=280,
            ),
            RawVariableSpec(
                code="LME_COPPER_CANCELLED_WARRANTS",
                name="LME Copper Cancelled Warrant Physical Outflow Ratio",
                description="Copper warrants that have been cancelled by the holder for physical loading out of the warehouse.",
                dataset_code="LME_DAILY_WAREHOUSE_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MT",
                commodity_code="COPPER",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1D",
                is_benchmark=False,
                display_order=290,
            ),
            RawVariableSpec(
                code="LME_ALUMINUM_TOTAL_STOCKS",
                name="LME Primary Aluminum Total Warehouse Stocks",
                description="Aggregate primary aluminum ingots and T-bars stored across global LME approved warehouse network.",
                dataset_code="LME_DAILY_WAREHOUSE_STOCKS",
                domain_code="INVENTORIES",
                unit_code="MT",
                commodity_code="ALUMINUM",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1D",
                is_benchmark=True,
                display_order=300,
            ),
            # =========================================================================
            # 9. DRILLING RIG COUNTS (BAKER HUGHES)
            # =========================================================================
            RawVariableSpec(
                code="RIG_COUNT_US_OIL",
                name="Baker Hughes US Oil Rotary Active Drilling Rig Count",
                description="Weekly count of active rotary drilling rigs exploring for or developing onshore and offshore crude oil deposits in the US.",
                dataset_code="BAKER_HUGHES_ROTARY_RIG_COUNT",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="COUNT",
                commodity_code="CL",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=True,
                display_order=310,
            ),
            RawVariableSpec(
                code="RIG_COUNT_US_GAS",
                name="Baker Hughes US Natural Gas Active Drilling Rig Count",
                description="Weekly count of active rotary drilling rigs exploring for dry natural gas deposits.",
                dataset_code="BAKER_HUGHES_ROTARY_RIG_COUNT",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="COUNT",
                commodity_code="NG",
                data_type="INTEGER",
                aggregation_method="LAST",
                default_transformation="DIFF_1W",
                is_benchmark=False,
                display_order=320,
            ),
            # =========================================================================
            # 10. CLIMATE & WEATHER (NOAA CPC)
            # =========================================================================
            RawVariableSpec(
                code="NOAA_ENSO_ONI_INDEX",
                name="NOAA Oceanic Niño Index (ONI) Sea Surface Anomaly",
                description="Three-month running average of sea surface temperature departures from normal in the Niño 3.4 region (El Niño / La Niña threshold: +/- 0.5°C).",
                dataset_code="NOAA_CPC_ENSO_OUTLOOK",
                domain_code="WEATHER",
                unit_code="INDEX_PTS",
                commodity_code=None,
                data_type="DECIMAL",
                aggregation_method="AVG",
                default_transformation="RAW_LEVEL",
                is_benchmark=True,
                display_order=330,
            ),
            # =========================================================================
            # 11. MACROECONOMIC & FOREX (FEDERAL RESERVE)
            # =========================================================================
            RawVariableSpec(
                code="FX_USD_EUR_SPOT_RATE",
                name="US Dollar to Euro Noon Buying Spot Exchange Rate",
                description="Certified foreign exchange rate published by the Federal Reserve Bank of New York for cable transfers in USD per EUR.",
                dataset_code="FEDERAL_RESERVE_H10_FX_RATES",
                domain_code="FX",
                unit_code="USD",
                commodity_code=None,
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="PCT_CHANGE_1D",
                is_benchmark=True,
                display_order=340,
            ),
            RawVariableSpec(
                code="FX_USD_CNY_SPOT_RATE",
                name="US Dollar to Chinese Yuan Onshore Spot Rate",
                description="Certified noon exchange rate in Chinese Yuan per US Dollar.",
                dataset_code="FEDERAL_RESERVE_H10_FX_RATES",
                domain_code="FX",
                unit_code="CNY",
                commodity_code=None,
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="PCT_CHANGE_1D",
                is_benchmark=False,
                display_order=350,
            ),
            # =========================================================================
            # 12. BRAZILIAN CROP ESTIMATES (CONAB)
            # =========================================================================
            RawVariableSpec(
                code="CONAB_BRAZIL_SOYBEANS_PRODUCTION",
                name="CONAB Brazil Total Soybeans Harvest Production Estimate",
                description="Official Brazilian Ministry of Agriculture (CONAB) monthly surveyed soybean production volume across Cerrado and Southern states.",
                dataset_code="CONAB_BRAZIL_GRAIN_HARVEST_SURVEY",
                domain_code="SUPPLY_DEMAND_BALANCES",
                unit_code="MT",
                commodity_code="SOYBEANS",
                data_type="DECIMAL",
                aggregation_method="SUM",
                default_transformation="DIFF_1M",
                is_benchmark=True,
                display_order=360,
            ),
            # =========================================================================
            # 13. MALAYSIAN PALM OIL BALANCE (MPOB)
            # =========================================================================
            RawVariableSpec(
                code="MPOB_PALM_OIL_ENDING_STOCKS",
                name="MPOB Malaysia Total Palm Oil Carryover Ending Stocks",
                description="Total official crude and processed palm oil inventories stored at Malaysian mills, refineries, and port bulk storage tanks.",
                dataset_code="MPOB_PALM_OIL_MONTHLY_BALANCE",
                domain_code="INVENTORIES",
                unit_code="MT",
                commodity_code="PALM_OIL",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1M",
                is_benchmark=True,
                display_order=370,
            ),
            # =========================================================================
            # 14. EUROPEAN CARBON EMISSIONS (EEX)
            # =========================================================================
            RawVariableSpec(
                code="EEX_EUA_AUCTION_CLEARING_PRICE",
                name="EEX European Union Allowance (EUA) Auction Clearing Price",
                description="Daily official clearing settlement price per metric ton of CO2 equivalent under the EU Emissions Trading System (ETS).",
                dataset_code="EEX_EUA_CARBON_AUCTION_RESULTS",
                domain_code="EXCHANGE_MARKET_DATA",
                unit_code="EUR",
                commodity_code="EUA_CARBON",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1D",
                is_benchmark=True,
                display_order=380,
            ),
            # =========================================================================
            # 15. BENCHMARK PHYSICAL CRUDE ASSESSMENTS (ARGUS & PLATTS)
            # =========================================================================
            RawVariableSpec(
                code="ARGUS_WTI_HOUSTON_DIFF",
                name="Argus WTI Houston Pipeline Physical Price Differential to WTI Cushing",
                description="Physical spot differential assessment for Light Sweet Crude delivered into Magellan East Houston (MEH) terminal versus NYMEX Cushing.",
                dataset_code="ARGUS_US_GULF_CRUDE_ASSESSMENTS",
                domain_code="PHYSICAL_MARKET",
                unit_code="USD_BBL",
                commodity_code="CL",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="SPREAD_DIFF",
                is_benchmark=True,
                display_order=390,
            ),
            RawVariableSpec(
                code="PLATTS_BRENT_DATED_PRICE",
                name="Platts Dated Brent Physical Cargo Assessment",
                description="Benchmark North Sea physical loading spot assessment for FOB Brent, Forties, Oseberg, Ekofisk, Troll, or WTI Midland cargoes.",
                dataset_code="PLATTS_NORTH_SEA_BRENT_ASSESSMENTS",
                domain_code="PHYSICAL_MARKET",
                unit_code="USD_BBL",
                commodity_code="BRENT",
                data_type="DECIMAL",
                aggregation_method="LAST",
                default_transformation="DIFF_1D",
                is_benchmark=True,
                display_order=400,
            ),
        ]
