# Generated by Django 5.2.17 on 2026-09-21 08:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0002_exchangeholiday_affected_product_groups_and_more'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('code', models.CharField(db_index=True, help_text="Canonical internal symbol (e.g. 'CL', 'BRENT', 'NG', 'CORN', 'GOLD')", max_length=32, unique=True)),
                ('name', models.CharField(help_text="Human-readable title (e.g. 'Light Sweet Crude Oil (WTI)', 'Henry Hub Natural Gas')", max_length=128)),
                ('sector', models.CharField(choices=[('ENERGY', 'Energy (Crude, Gas, Power, Refined)'), ('AGRICULTURE', 'Agriculture (Grains, Oilseeds, Softs)'), ('LIVESTOCK', 'Livestock & Dairy'), ('METALS_BASE', 'Industrial / Base Metals'), ('METALS_PRECIOUS', 'Precious Metals'), ('FREIGHT_BULK', 'Bulk Freight & Shipping'), ('ENVIRONMENTAL', 'Environmental & Carbon Allowances')], db_index=True, help_text='High-level commodity sector classification', max_length=32)),
                ('group', models.CharField(db_index=True, help_text="Industry grouping (e.g. 'CRUDE_OIL', 'REFINED_PRODUCTS', 'GRAINS', 'SOFTS', 'PRECIOUS_METALS')", max_length=64)),
                ('standard_lot_size', models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='Standard contract physical lot size in benchmark units (e.g. 1000 bbl, 5000 bu, 100 toz)', max_digits=16)),
                ('minimum_tick_size', models.DecimalField(decimal_places=6, default=Decimal('0.01'), help_text='Minimum allowable price fluctuation (e.g. 0.01 for WTI, 0.001 for NG, 0.0025 for Corn)', max_digits=12)),
                ('tick_value', models.DecimalField(decimal_places=4, default=Decimal('10.00'), help_text='Monetary value of one minimum price fluctuation per contract (e.g. $10.00 for WTI, $12.50 for Corn)', max_digits=12)),
                ('tick_currency', models.CharField(default='USD', help_text='Currency ISO code of tick value (e.g. USD, EUR, MYR, INR)', max_length=3)),
                ('settlement_method', models.CharField(choices=[('PHYSICAL', 'Physical Delivery'), ('CASH', 'Cash Settlement')], default='PHYSICAL', help_text='Default settlement mechanism of benchmark contract', max_length=16)),
                ('hs_code', models.CharField(blank=True, default='', help_text='Harmonized System 6-digit tariff code (e.g. 2709.00 for crude oil, 1005.90 for corn)', max_length=16)),
                ('deliverable_grade_standard', models.CharField(blank=True, default='', help_text="Primary deliverable grade specification (e.g. 'U.S. No. 2 Yellow Corn', 'API 37-42°, Sulfur <= 0.42%')", max_length=256)),
                ('quality_specifications', models.JSONField(blank=True, default=dict, help_text='Structured physical/chemical parameters: API gravity, sulfur, moisture, purity, test weight, etc.')),
                ('primary_delivery_hub', models.CharField(blank=True, default='', help_text="Benchmark pricing point / physical delivery terminal (e.g. 'Cushing, Oklahoma', 'Henry Hub, Louisiana')", max_length=128)),
                ('delivery_hub_details', models.JSONField(blank=True, default=dict, help_text='Hub geography, coordinates, storage terminals, and pipeline interconnects')),
                ('crop_year_start_month', models.PositiveSmallIntegerField(blank=True, help_text='Calendar month (1-12) marking crop marketing year start (e.g. 9 for Sept US Corn/Soybeans)', null=True)),
                ('peak_production_months', models.JSONField(blank=True, default=list, help_text='List of calendar months with peak harvest or production output')),
                ('peak_demand_months', models.JSONField(blank=True, default=list, help_text='List of calendar months with peak seasonal consumption')),
                ('seasonality_notes', models.TextField(blank=True, default='', help_text='Institutional commentary on seasonal supply, demand, and basis tendencies')),
                ('description', models.TextField(blank=True, default='', help_text='Comprehensive commercial scope and market profile')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if commodity is actively tracked by analytics')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='UI and reporting ordering rank')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata, conversion ratios, and external identifiers')),
                ('base_unit', models.ForeignKey(help_text='Base physical unit of measure (e.g. BBL, MMBTU, BU, MT, TOZ, LBS)', on_delete=django.db.models.deletion.PROTECT, related_name='base_commodities', to='metadata.unitmaster')),
                ('pricing_unit', models.ForeignKey(help_text='Default price quote unit (e.g. USD_BBL, USD_MMBTU, USC_BU, USD_TOZ, USD_MT)', on_delete=django.db.models.deletion.PROTECT, related_name='pricing_commodities', to='metadata.unitmaster')),
                ('primary_exchange', models.ForeignKey(help_text='Global pricing benchmark venue (e.g. NYMEX for WTI, ICE_EU for Brent, COMEX for Gold)', on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_commodities', to='exchanges.exchangemaster')),
                ('standard_lot_unit', models.ForeignKey(help_text='Physical unit for contract lot size', on_delete=django.db.models.deletion.PROTECT, related_name='lot_commodities', to='metadata.unitmaster')),
            ],
            options={
                'verbose_name': 'Commodity Master',
                'verbose_name_plural': 'Commodities Master',
                'ordering': ['sector', 'display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CommodityExchangeListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the database record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the database record was last modified')),
                ('ticker_symbol', models.CharField(db_index=True, help_text="Exchange-specific ticker symbol (e.g. 'CL' on NYMEX, 'CRUDEOIL' on MCX, 'GC' on COMEX)", max_length=32)),
                ('contract_size', models.DecimalField(decimal_places=4, help_text='Contract lot size on this specific venue', max_digits=16)),
                ('settlement_method', models.CharField(choices=[('PHYSICAL', 'Physical Delivery'), ('CASH', 'Cash Settlement')], default='PHYSICAL', help_text='Settlement mechanism on this specific exchange (e.g. MCX Crude is Cash, NYMEX is Physical)', max_length=16)),
                ('is_primary_benchmark', models.BooleanField(default=False, help_text='Flag indicating if this venue is the global reference pricing contract')),
                ('liquidity_tier', models.CharField(choices=[('BENCHMARK', 'Global Benchmark Volume'), ('HIGH', 'High Institutional Volume & Open Interest'), ('ACTIVE', 'Active Liquid Regional Contract')], default='ACTIVE', help_text='Market liquidity and open interest tier', max_length=32)),
                ('typical_daily_volume', models.PositiveIntegerField(default=0, help_text='Typical average daily contract volume (ADV)')),
                ('typical_open_interest', models.PositiveIntegerField(default=0, help_text='Typical active open interest (OI) in contracts')),
                ('trading_currency', models.CharField(default='USD', help_text='Trading quotation currency (e.g. USD, INR, CNY, EUR, MYR)', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this listing is actively monitored')),
                ('contract_unit', models.ForeignKey(help_text="Unit of measure for this venue's contract lot", on_delete=django.db.models.deletion.PROTECT, related_name='listing_units', to='metadata.unitmaster')),
                ('exchange', models.ForeignKey(help_text='The trading venue where this contract executes', on_delete=django.db.models.deletion.PROTECT, related_name='commodity_listings', to='exchanges.exchangemaster')),
                ('commodity', models.ForeignKey(help_text='The underlying physical commodity', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_listings', to='commodities.commoditymaster')),
            ],
            options={
                'verbose_name': 'Commodity Exchange Listing',
                'verbose_name_plural': 'Commodity Exchange Listings',
                'ordering': ['commodity', '-is_primary_benchmark', '-typical_daily_volume'],
            },
        ),
        migrations.AddIndex(
            model_name='commoditymaster',
            index=models.Index(fields=['sector', 'is_active'], name='commodities_sector_757657_idx'),
        ),
        migrations.AddIndex(
            model_name='commoditymaster',
            index=models.Index(fields=['group', 'is_active'], name='commodities_group_f1e531_idx'),
        ),
        migrations.AddIndex(
            model_name='commodityexchangelisting',
            index=models.Index(fields=['exchange', 'ticker_symbol'], name='commodities_exchang_04c2d8_idx'),
        ),
        migrations.AddIndex(
            model_name='commodityexchangelisting',
            index=models.Index(fields=['commodity', 'is_primary_benchmark'], name='commodities_commodi_96666a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commodityexchangelisting',
            unique_together={('commodity', 'exchange')},
        ),
    ]
